import { database, hash, cookie, setCookie, presenterAuthenticated } from '../../../db/server';
import { defaults, skills, type Config, type Idea } from '../../../lib/workshop';
import { reply, failure, clean, invalidate, snapshot, readCode, unavailable, type Session } from '../../../lib/snapshot';
export const dynamic='force-dynamic';
async function context(req:Request,code:string){const db=database();const session=await db.prepare('SELECT * FROM sessions WHERE code = ?').bind(code).first<Session>();if(!session)return null;const admin=cookie(req,'admin_'+code);const isPresenter=presenterAuthenticated(req)||(!!admin&&await hash(admin)===session.adminHash);const participant=cookie(req,'student_'+code);const me=participant?await db.prepare('SELECT id,nickname FROM participants WHERE id = ? AND code = ?').bind(participant,code).first<{id:string;nickname:string}>():null;return {db,session,config:JSON.parse(session.config) as Config,isPresenter,me};}
export async function GET(req:Request){try{return await snapshot(req,readCode(req));}catch(e){return unavailable(e);}}
export async function POST(req:Request){let code='';try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return failure('Invalid request origin.',403);if(Number(req.headers.get('content-length')||0)>40000)return failure('Request too large.',413);let b:Record<string,unknown>;try{b=await req.json() as Record<string,unknown>;}catch{return failure('Invalid request.');}if(!b||typeof b!=='object')return failure('Invalid request.');const action=b.action;code=clean(b.code,20).toUpperCase();const db=database();
 if(action==='create'){const config={...defaults,...settings(b),revision:crypto.randomUUID()};const key=crypto.randomUUID()+crypto.randomUUID();const digits=new Uint32Array(1);crypto.getRandomValues(digits);const newCode='UTAS-'+String(100000+digits[0]%900000);await db.prepare('INSERT INTO sessions (code,adminHash,config,created) VALUES (?,?,?,?)').bind(newCode,await hash(key),JSON.stringify(config),Date.now()).run();return reply({code:newCode,key},201,{'Set-Cookie':setCookie(req,'admin_'+newCode,key)});}
 const c=await context(req,code);if(!c)return failure('Workshop not found.',404);const {config,isPresenter,me}=c;
 if(action==='unlock'){const key=clean(b.key,200);if(await hash(key)!==c.session.adminHash)return failure('The presenter key is incorrect.',403);return reply({ok:true},200,{'Set-Cookie':setCookie(req,'admin_'+code,key)});}
 if(action==='join'){if(config.ended)return failure('This workshop has ended.');if(me)return reply({ok:true});let nickname=clean(b.nickname,40);if(!nickname&&!config.anonymous)return failure('Please enter a nickname.');if(!nickname)nickname='Anonymous';const id=crypto.randomUUID();await db.prepare('INSERT INTO participants (id,code,nickname,created) VALUES (?,?,?,?)').bind(id,code,nickname,Date.now()).run();return reply({ok:true},201,{'Set-Cookie':setCookie(req,'student_'+code,id)});}
 if(action==='deleteWorkshop'){if(!isPresenter)return failure('Presenter access required.',403);if(clean(b.confirm,20).toUpperCase()!==code)return failure('Type the workshop code to confirm.');
  // One transaction: children first, because ideas and participants reference the session.
  await db.batch([db.prepare('DELETE FROM votes WHERE code=?').bind(code),db.prepare('DELETE FROM reflections WHERE code=?').bind(code),db.prepare('DELETE FROM ideas WHERE code=?').bind(code),db.prepare('DELETE FROM participants WHERE code=?').bind(code),db.prepare('DELETE FROM sessions WHERE code=?').bind(code)]);return reply({ok:true});}
 if(action==='control'||action==='moderate'||action==='demo'){if(!isPresenter)return failure('Presenter access required.',403);
 if(action==='control'){const patch=b.patch as Record<string,unknown>||{};const next={...config};Object.assign(next,settings(patch,true));for(const field of ['paused','submissionsOpen','votingOpen','ended','liveResults'] as const)if(typeof patch[field]==='boolean')next[field]=patch[field] as boolean;if(Number.isInteger(patch.stage)&&Number(patch.stage)>=0&&Number(patch.stage)<=8){next.stage=Number(patch.stage);if(next.stage!==5)next.votingOpen=false;}if(typeof patch.screen==='string'&&['stage','qr','wall','voting','spotlight','skills','wow'].includes(patch.screen))next.screen=patch.screen;if(patch.spotlight===null||typeof patch.spotlight==='string')next.spotlight=patch.spotlight as string|null;if(patch.timerEnd===null||typeof patch.timerEnd==='number')next.timerEnd=patch.timerEnd as number|null;if(Array.isArray(patch.selected))next.selected=patch.selected.filter(x=>typeof x==='string').slice(0,100);if(patch.canvas&&typeof patch.canvas==='object')next.canvas=Object.fromEntries(Object.entries(patch.canvas).map(([k,v])=>[clean(k,40),clean(v,5000)]));if(typeof patch.prompt==='string')next.prompt=clean(patch.prompt,25000);if(Number.isInteger(patch.reveal))next.reveal=Math.max(0,Math.min(8,Number(patch.reveal)));if(next.votingOpen){next.stage=5;const finalists=await db.prepare("SELECT COUNT(*) AS n FROM ideas WHERE code=? AND shortlisted=1 AND status='approved'").bind(code).first<{n:number}>();if(!finalists?.n)return failure('Shortlist and approve at least one idea before voting.');}if(next.ended){next.votingOpen=false;next.submissionsOpen=false;}next.revision=crypto.randomUUID();const saved=await db.prepare('UPDATE sessions SET config=? WHERE code=? AND config=?').bind(JSON.stringify(next),code,c.session.config).run();if(!saved.meta.changes)return failure('Another presenter control changed. Please retry.',409);return reply({ok:true});}
 if(action==='demo'){const n=await db.prepare('SELECT COUNT(*) AS n FROM ideas WHERE code=?').bind(code).first<{n:number}>();if(n?.n)return failure('Sample ideas can only be added to an empty workshop.');const samples=[['Medication reminders','Students forget when to take medication.','problem'],['Appointment assistant','Help students keep track of clinic appointments.','idea'],['Understand health information','Explain complex information in clear Arabic and English.','idea'],['Healthy habits companion','Help students build consistent sleep and movement routines.','solution'],['Voice-first reminders','Make reminders accessible through Arabic voice notifications.','solution'],['A private student health journal','Keep personal notes under student control.','idea']];await db.batch(samples.map(([title,text,type],i)=>db.prepare("INSERT INTO ideas (id,code,participant,nickname,type,parent,title,text,status,shortlisted,highlighted,sortOrder,created) VALUES (?,?,?,'Demo team',?,NULL,?,?,'approved',0,0,0,?)").bind(crypto.randomUUID(),code,'demo',type,title,text,Date.now()-i*1000)));return reply({ok:true});}
 const id=clean(b.id,100);const idea=await db.prepare('SELECT * FROM ideas WHERE id=? AND code=?').bind(id,code).first<Idea>();if(!idea)return failure('Idea not found.',404);const op=b.op;if(op==='delete'){await db.batch([db.prepare('DELETE FROM votes WHERE code=? AND idea IN (SELECT id FROM ideas WHERE code=? AND (id=? OR parent=?))').bind(code,code,id,id),db.prepare("UPDATE ideas SET status='deleted',shortlisted=0 WHERE code=? AND (id=? OR parent=?)").bind(code,id,id)]);}
 else if(op==='approve'||op==='hide'){await db.prepare('UPDATE ideas SET status=?,shortlisted=CASE WHEN ?=? THEN 0 ELSE shortlisted END WHERE id=? AND code=?').bind(op==='approve'?'approved':'hidden',op,'hide',id,code).run();}
 else if(op==='shortlist'){if(idea.type==='comment')return failure('Shortlist an idea, not a comment.');if(config.votingOpen)return failure('Close voting before changing finalists.');if(idea.status!=='approved')return failure('Approve this idea first.');await db.prepare('UPDATE ideas SET shortlisted=? WHERE id=? AND code=?').bind(idea.shortlisted?0:1,id,code).run();}
 else if(op==='highlight'){await db.prepare('UPDATE ideas SET highlighted=? WHERE id=? AND code=?').bind(idea.highlighted?0:1,id,code).run();}
 else if(op==='edit'){const text=clean(b.text,1500),title=clean(b.title,100);if(!text||!title)return failure('Title and contribution are required.');await db.prepare('UPDATE ideas SET title=?,text=? WHERE id=? AND code=?').bind(title,text,id,code).run();}
 else if(op==='order'){await db.prepare('UPDATE ideas SET sortOrder=? WHERE id=? AND code=?').bind(Math.max(-10000,Math.min(10000,Number(b.order)||0)),id,code).run();}
 else if(op==='merge'){if(config.votingOpen)return failure('Close voting before merging ideas.');const target=await db.prepare("SELECT * FROM ideas WHERE code=? AND id=? AND status='approved'").bind(code,clean(b.target,100)).first<Idea>();if(!target||target.id===id)return failure('Choose a different approved idea.');const merged=target.text+'\n\n'+idea.text;if(merged.length>1500)return failure('Combined text exceeds 1500 characters. Shorten the ideas before merging.');await db.batch([db.prepare('UPDATE ideas SET text=? WHERE code=? AND id=?').bind(merged,code,target.id),db.prepare('UPDATE ideas SET parent=? WHERE code=? AND parent=?').bind(target.id,code,id),db.prepare("UPDATE ideas SET status='hidden',shortlisted=0 WHERE code=? AND id=?").bind(code,id),db.prepare('INSERT OR IGNORE INTO votes(code,participant,idea) SELECT code,participant,? FROM votes WHERE code=? AND idea=?').bind(target.id,code,id),db.prepare('DELETE FROM votes WHERE code=? AND idea=?').bind(code,id)]);}
 else return failure('Unknown moderation action.');return reply({ok:true});}
 if(!me)return failure('Join the workshop first.',401);if(config.ended)return failure('This workshop has ended.');if(config.paused)return failure('The workshop is paused. Please wait for the presenter.');
 if(action==='editOwn'){
 if(!config.submissionsOpen)return failure('Editing is closed.');
 const id=clean(b.id,100),title=clean(b.title,100),text=clean(b.text,1500);
 if(!title||text.length<3)return failure('A title and at least three characters are required.');
 const idea=await db.prepare("SELECT * FROM ideas WHERE id=? AND code=? AND type!='comment'").bind(id,code).first<Idea>();
 if(!idea||idea.participant!==me.id)return failure('You can only edit your own ideas.',403);
 if(idea.shortlisted||!['pending','approved'].includes(idea.status))return failure('This idea cannot be edited. Ask the presenter for help.');
 const status=config.moderated?'pending':'approved';
 const saved=await db.prepare("UPDATE ideas SET title=?,text=?,status=? WHERE id=? AND code=? AND participant=? AND shortlisted=0 AND status IN ('pending','approved') AND EXISTS(SELECT 1 FROM sessions WHERE code=? AND config=?)").bind(title,text,status,id,code,me.id,code,c.session.config).run();
 if(!saved.meta.changes)return failure('The workshop changed. Please refresh and retry.',409);
 return reply({ok:true,status});
 }
 if(action==='comment'){

 if(!config.submissionsOpen)return failure('Discussion is closed.');
 const parent=clean(b.parent,100),text=clean(b.text,1500),id=clean(b.id,100);
 if(text.length<3)return failure('Please write at least three characters.');
 if(!/^[a-f0-9-]{36}$/.test(id))return failure('Invalid comment identifier.');
 const status=config.moderated?'pending':'approved';
 const saved=await db.prepare("INSERT OR IGNORE INTO ideas (id,code,participant,nickname,type,parent,title,text,status,shortlisted,highlighted,sortOrder,created) SELECT ?,?,?,?,'comment',?,'Comment',?,?,0,0,0,? WHERE EXISTS (SELECT 1 FROM ideas WHERE id=? AND code=? AND status='approved' AND type!='comment') AND EXISTS (SELECT 1 FROM sessions WHERE code=? AND json_extract(config,'$.paused')=0 AND json_extract(config,'$.submissionsOpen')=1 AND json_extract(config,'$.ended')=0) AND (SELECT COUNT(*) FROM ideas WHERE code=? AND parent=? AND participant=? AND type='comment' AND status!='deleted')<20").bind(id,code,me.id,me.nickname,parent,text,status,Date.now(),parent,code,code,code,parent,me.id).run();
 if(!saved.meta.changes){const existing=await db.prepare("SELECT id FROM ideas WHERE id=? AND code=? AND participant=? AND type='comment'").bind(id,code,me.id).first();if(existing)return reply({ok:true,status});return failure('This idea is unavailable, discussion is closed, or your comment limit is reached.');}
 return reply({ok:true,status},201);
 }
 if(action==='submit'){
if(!config.submissionsOpen)return failure('Submissions are closed.');const types:Record<number,string>={1:'problem',2:'idea',3:'solution',4:'improvement',7:'suggestion'};const type=types[config.stage];if(!type)return failure('Submissions are not open at this stage.');const text=clean(b.text,1500);if(text.length<3)return failure('Please write at least three characters.');let parent:string|null=null;if(type==='solution'||type==='improvement'){parent=config.spotlight;if(!parent)return failure('Wait for the presenter to select an idea.');const exists=await db.prepare("SELECT id FROM ideas WHERE code=? AND id=? AND status='approved'").bind(code,parent).first();if(!exists)return failure('The selected idea is no longer available.');}const id=clean(b.id,100);if(!/^[a-f0-9-]{36}$/.test(id))return failure('Invalid submission identifier.');const title=clean(b.title,100)||(text.length<=65?text:text.slice(0,65).replace(/\s+\S*$/,'')+'…');const status=config.moderated?'pending':'approved';const sql=`INSERT OR IGNORE INTO ideas (id,code,participant,nickname,type,parent,title,text,status,shortlisted,highlighted,sortOrder,created) SELECT ?,?,?,?,?,?,?,?,?,0,0,0,? WHERE (SELECT COUNT(*) FROM ideas WHERE code=? AND participant=? AND type=? AND status!='deleted') < ? AND EXISTS (SELECT 1 FROM sessions WHERE code=? AND json_extract(config,'$.stage')=? AND json_extract(config,'$.paused')=0 AND json_extract(config,'$.submissionsOpen')=1 AND json_extract(config,'$.ended')=0)`;const r=await db.prepare(sql).bind(id,code,me.id,me.nickname,type,parent,title,text,status,Date.now(),code,me.id,type,config.multiple?20:1,code,config.stage).run();if(!r.meta.changes){const existing=await db.prepare('SELECT id FROM ideas WHERE id=? AND participant=?').bind(id,me.id).first();if(existing)return reply({ok:true,status});return failure('Submission limit reached or the stage has changed.');}return reply({ok:true,status},201);}
 if(action==='vote'){const id=clean(b.id,100);const result=await db.prepare(`INSERT OR IGNORE INTO votes(code,participant,idea) SELECT ?,?,? WHERE EXISTS (SELECT 1 FROM sessions WHERE code=? AND json_extract(config,'$.votingOpen')=1 AND json_extract(config,'$.paused')=0 AND json_extract(config,'$.ended')=0 AND (SELECT COUNT(*) FROM votes WHERE code=? AND participant=?) < json_extract(config,'$.maxVotes')) AND EXISTS(SELECT 1 FROM ideas WHERE code=? AND id=? AND shortlisted=1 AND status='approved')`).bind(code,me.id,id,code,code,me.id,code,id).run();if(!result.meta.changes)return failure('Voting is closed, this idea is unavailable, or you have used your votes.');return reply({ok:true});}
 if(action==='reflect'){const skill=clean(b.skill,100);if(config.stage!==8||!skills.includes(skill))return failure('Reflection is not available.');await db.prepare('INSERT INTO reflections(code,participant,skill) VALUES(?,?,?) ON CONFLICT(code,participant) DO UPDATE SET skill=excluded.skill').bind(code,me.id,skill).run();return reply({ok:true});}
 return failure('Unknown action.');
 }catch(e){console.error('Workshop action failed',e);return failure('Unable to save right now. Keep your text and retry.',503);}finally{if(code)invalidate(code);}}
function settings(b:Record<string,unknown>,partial=false){const out:Partial<Config>={};for(const field of ['name','challenge','question','description'] as const){if(typeof b[field]==='string'){const value=clean(b[field],field==='question'||field==='description'?1000:100);if(value||field==='description')out[field]=value;}}if(!partial){out.name=out.name||defaults.name;out.challenge=out.challenge||defaults.challenge;out.question=out.question||defaults.question;}for(const f of ['anonymous','moderated','liveResults','multiple'] as const)if(typeof b[f]==='boolean')out[f]=b[f] as boolean;if(['en','ar','both'].includes(String(b.language)))out.language=b.language as Config['language'];if(Number.isInteger(b.maxVotes)&&Number(b.maxVotes)>=1&&Number(b.maxVotes)<=10)out.maxVotes=Number(b.maxVotes);return out;}


