"use client";
import {useState,useEffect} from 'react';
import {Plus,ArrowUpRight,KeyRound} from 'lucide-react';
import {Brand,action} from '../../lib/client';
import {defaults,type Config} from '../../lib/workshop';
import {Settings} from '../../lib/settings';
import Console from '../../lib/console';
export default function Presenter(){const [code,setCode]=useState(''),[entry,setEntry]=useState(''),[key,setKey]=useState(''),[mode,setMode]=useState('login'),[form,setForm]=useState<Config>({...defaults}),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{const q=new URLSearchParams(location.search).get('code');if(q)setCode(q.toUpperCase());const last=localStorage.getItem('lastPresenterCode');if(last)setEntry(last)},[]);async function submit(){setBusy(true);setError('');try{if(mode==='create'){const r=await action({action:'create',...form});sessionStorage.setItem('newPresenterKey',r.key);localStorage.setItem('lastPresenterCode',r.code);location.href='/presenter?code='+r.code;}else{const c=entry.trim().toUpperCase();await action({action:'unlock',code:c,key});localStorage.setItem('lastPresenterCode',c);location.href='/presenter?code='+c;}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(code)return <Console code={code}/>;
 return <main className="center-page"><Brand/><span className="eyebrow">PRESENTER CONTROL CENTER</span><h1>{mode==='create'?'Create your workshop':'Let’s lead something great.'}</h1><p>{mode==='create'?'Choose a challenge. Your students will do the rest.':'Open an existing session with your presenter key, or start a fresh workshop.'}</p><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Open workshop</button><button className={mode==='create'?'active':''} onClick={()=>setMode('create')}><Plus size={13}/> Create workshop</button></div><form className="panel stack" onSubmit={e=>{e.preventDefault();void submit()}}>{mode==='create'?<><label>Start from a challenge<select value={form.challenge} onChange={e=>{const challenge=e.target.value;setForm({...form,challenge,question:challenge==='Your Healthcare Assistant'?defaults.question:`How can we use technology and AI to create a useful ${challenge.toLowerCase()} for university students?`})}}>{['Your Healthcare Assistant','Smart Campus','AI Study Assistant','Environmental Assistant','Tourism Assistant','Career Assistant','Agriculture Assistant','Safety Assistant','Custom Challenge',...(!['Your Healthcare Assistant','Smart Campus','AI Study Assistant','Environmental Assistant','Tourism Assistant','Career Assistant','Agriculture Assistant','Safety Assistant','Custom Challenge'].includes(form.challenge)?[form.challenge]:[])].map(c=><option key={c}>{c}</option>)}</select></label><Settings value={form} onChange={setForm}/></>:<><label>Workshop code<input value={entry} onChange={e=>setEntry(e.target.value.toUpperCase())} required placeholder="UTAS-123456"/></label><label>Presenter key<input value={key} onChange={e=>setKey(e.target.value)} required type="password" placeholder="Your private presenter key" autoComplete="current-password"/></label><p className="inline-help"><KeyRound size={14}/> Your key is provided when you create a workshop. Keep it private.</p></>}{error&&<div className="error" role="alert">{error}</div>}<button disabled={busy} className="btn primary full-width">{busy?'Opening…':mode==='create'?'Start workshop':'Open control center'} <ArrowUpRight size={18}/></button></form><a className="muted" href="/join">Joining as a student? Enter here.</a></main>;
}
