"use client";
import {useState,useEffect,useCallback} from 'react';
import {Command,X,Clock,Users,Lightbulb} from 'lucide-react';
import type {Snapshot,Language} from './workshop';
import {skills,skillArabic} from './workshop';
export async function action(body:Record<string,unknown>){const r=await fetch('/api/workshop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {error?:string;code:string;key:string;ok?:boolean;status?:string};if(!r.ok)throw new Error(data.error||'Unable to save. Please retry.');return data;}
export function useWorkshop(code:string){const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[connected,setConnected]=useState(false);const refresh=useCallback(async()=>{if(!code)return;try{const r=await fetch('/api/workshop?code='+encodeURIComponent(code),{cache:'no-store'});const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError((e as Error).message)}},[code]);useEffect(()=>{if(!code)return;setData(null);void refresh();const stream=new EventSource('/api/events?code='+encodeURIComponent(code));stream.onopen=()=>setConnected(true);stream.onmessage=e=>{setData(JSON.parse(e.data));setError('');setConnected(true)};stream.onerror=()=>setConnected(false);stream.addEventListener('unavailable',()=>setConnected(false));const recover=setInterval(()=>{if(stream.readyState!==EventSource.OPEN)void refresh()},5000);const onVisible=()=>{if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',onVisible);return()=>{stream.close();clearInterval(recover);document.removeEventListener('visibilitychange',onVisible)}},[code,refresh]);return{data,error,connected,refresh};}
export function Brand(){return <a className="brand" href="/"><span className="brand-icon"><Command size={20}/></span>AI COLLAB <b>LAB</b></a>}
export function T({en,ar,lang}:{en:string;ar:string;lang:Language}){return <>{lang==='ar'?ar:en}{lang==='both'&&<span className="arabic" dir="rtl">{ar}</span>}</>}
export function LanguageSwitch({lang,onChange}:{lang:Language;onChange:(v:Language)=>void}){return <div className="language" aria-label="Language">{(['en','ar','both'] as Language[]).map((l,i)=><button key={l} className={lang===l?'active':''} onClick={()=>onChange(l)}>{['EN','العربية','EN / ع'][i]}</button>)}</div>}
export function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[onClose]);return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{title}</h2><button className="btn small icon-btn secondary" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</section></div>}
export function Timer({end}:{end:number|null}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);if(!end)return null;const sec=Math.max(0,Math.ceil((end-now)/1000));return <span className="timer"><Clock size={19}/> {String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}{sec===0&&<small className="muted"> · Time’s up</small>}</span>}
export function Empty({title='The next great idea is on its way',text='Student contributions will appear here as they arrive.'}:{title?:string;text?:string}){return <div className="empty"><Lightbulb size={30}/><h3>{title}</h3>{text}</div>}
export function download(filename:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Results({data,reflection=false}:{data:Snapshot;reflection?:boolean}){const entries=reflection?Object.entries(data.reflection).sort((a,b)=>b[1]-a[1]):data.ideas.filter(i=>i.shortlisted&&i.status==='approved').sort((a,b)=>(b.votes||0)-(a.votes||0)).map(i=>[i.title,i.votes||0] as [string,number]);const max=Math.max(1,...entries.map(i=>i[1]));return <div className="results">{entries.length?entries.map(([name,count],i)=><div className="result" key={name+i}><div className="result-title"><strong><span className="muted">{String(i+1).padStart(2,'0')} / </span>{reflection&&data.config.language==='ar'?(skillArabic[skills.indexOf(name)]||name):name}</strong><span>{count}</span></div><div className="bar-track"><div className="bar-fill" style={{width:count/max*100+'%',background:i===0?'var(--accent)':i===1?'var(--purple)':'#9ddcdd'}}/></div><small>{count} {reflection?'students':'votes'}</small></div>):<Empty title="Ready for the first vote" text="Results will update as the team votes."/>}</div>}


