import { sqliteTable, text, integer, primaryKey, index, blob } from 'drizzle-orm/sqlite-core';
export const sessions=sqliteTable('sessions',{code:text('code').primaryKey(),adminHash:text('adminHash').notNull(),config:text('config').notNull(),created:integer('created').notNull(),/** Set on a team room: the main workshop it belongs to. */parent:text('parent')},t=>[index('idx_sessions_parent').on(t.parent)]);
export const participants=sqliteTable('participants',{id:text('id').primaryKey(),code:text('code').notNull().references(()=>sessions.code),nickname:text('nickname').notNull(),created:integer('created').notNull(),/** Team rooms: the participant's id in the main workshop. */member:text('member'),/** member | lead | guest (guests read and comment only). */role:text('role').notNull().default('member')},t=>[index('idx_participants_code').on(t.code),index('idx_participants_member').on(t.member)]);
export const ideas=sqliteTable('ideas',{id:text('id').primaryKey(),code:text('code').notNull().references(()=>sessions.code),participant:text('participant').notNull(),nickname:text('nickname').notNull(),type:text('type').notNull(),parent:text('parent'),title:text('title').notNull(),text:text('text').notNull(),status:text('status').notNull(),shortlisted:integer('shortlisted').notNull().default(0),highlighted:integer('highlighted').notNull().default(0),sortOrder:integer('sortOrder').notNull().default(0),created:integer('created').notNull()},t=>[index('idx_ideas_code').on(t.code)]);
export const votes=sqliteTable('votes',{code:text('code').notNull(),participant:text('participant').notNull(),idea:text('idea').notNull()},t=>[primaryKey({columns:[t.code,t.participant,t.idea]}),index('idx_votes_code_idea').on(t.code,t.idea)]);
export const reflections=sqliteTable('reflections',{code:text('code').notNull(),participant:text('participant').notNull(),skill:text('skill').notNull()},t=>[primaryKey({columns:[t.code,t.participant]})]);
/** Application-wide settings edited by the presenter admin (branding, About page). One JSON value per key. */
export const appSettings=sqliteTable('app_settings',{key:text('key').primaryKey(),value:text('value').notNull(),updated:integer('updated').notNull()});
/** Machine-translation cache shared by all viewers: key = sha256(target + newline + source text). */
export const translations=sqliteTable('translations',{key:text('key').primaryKey(),target:text('target').notNull(),text:text('text').notNull(),provider:text('provider').notNull(),created:integer('created').notNull()});
/** Files shared inside team rooms (images and PDFs, 3 MB at most). Stored in the database so backups and deletes include them. */
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),code:text('code').notNull(),participant:text('participant').notNull(),nickname:text('nickname').notNull(),name:text('name').notNull(),type:text('type').notNull(),size:integer('size').notNull(),data:blob('data').notNull(),status:text('status').notNull(),created:integer('created').notNull()},t=>[index('idx_uploads_code').on(t.code)]);
/** Pieces of a file being uploaded (each under the proxy's request limit); removed once the file is assembled or after an hour. */
export const uploadChunks=sqliteTable('upload_chunks',{id:text('id').notNull(),idx:integer('idx').notNull(),code:text('code').notNull(),participant:text('participant').notNull(),data:blob('data').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.id,t.idx]})]);
/** Quick reactions (👍 💡 ❓ 🔥) on ideas and comments: one of each per person. */
export const reactions=sqliteTable('reactions',{code:text('code').notNull(),idea:text('idea').notNull(),participant:text('participant').notNull(),emoji:text('emoji').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.code,t.idea,t.participant,t.emoji]}),index('idx_reactions_code').on(t.code)]);
