"use client";

import {appUrl} from "./urls";
import {useState,useEffect,useCallback,useRef,createContext,useContext,useSyncExternalStore} from 'react';
import {Command,X,Clock,Lightbulb,Sun,Moon,Monitor} from 'lucide-react';
import type {Snapshot,Language} from './workshop';
import {skills,skillArabic} from './workshop';
import {typeMeta} from './learning';
import {useUiLang,setUiLang,getUiLang,translateError,tx,type UiLang} from './i18n';
import {useAppInfo} from './app-info-client';
export async function action(body:Record<string,unknown>){const r=await fetch(appUrl('/api/workshop'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data:{error?:string;code:string;key:string;ok?:boolean;status?:string};try{data=await r.json()}catch{throw new Error(translateError('The workshop service did not respond. Your text is still here — please retry.',getUiLang()))}if(!r.ok)throw new Error(translateError(data.error||'Unable to save. Please retry.',getUiLang()));return data;}
export function useWorkshop(code:string){const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[connected,setConnected]=useState(false);const refresh=useCallback(async()=>{if(!code)return;try{const r=await fetch(appUrl('/api/workshop?code=')+encodeURIComponent(code),{cache:'no-store'});const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError(translateError((e as Error).message,getUiLang())||tx(getUiLang(),'Connection lost. Retrying…','انقطع الاتصال. جارٍ إعادة المحاولة…'))}},[code]);useEffect(()=>{setData(null);if(code)void refresh()},[code,refresh]);useEffect(()=>{if(!code)return;const stream=new EventSource(appUrl('/api/events?code=')+encodeURIComponent(code));stream.onopen=()=>setConnected(true);stream.onmessage=e=>{try{setData(JSON.parse(e.data));setError('');setConnected(true)}catch{/* partial frame: the next snapshot replaces it */}};stream.onerror=()=>setConnected(false);stream.addEventListener('unavailable',()=>setConnected(false));const recover=setInterval(()=>{if(stream.readyState!==EventSource.OPEN)void refresh()},5000);const onVisible=()=>{if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',onVisible);return()=>{stream.close();clearInterval(recover);document.removeEventListener('visibilitychange',onVisible)}},[code,refresh,data?.me?.id,data?.isPresenter]);return{data,error,connected,refresh};}
/** Logo text comes from the admin's application settings. */
export function BrandText(){const info=useAppInfo();return <>{info.logoText}{info.logoText&&info.logoAccent?' ':''}{info.logoAccent&&<b>{info.logoAccent}</b>}</>}
export function Brand({size=20}:{size?:number}){const info=useAppInfo();return <a className="brand" href={appUrl("/")} aria-label={info.name}><span className="brand-icon"><Command size={size}/></span><BrandText/></a>}
export function T({en,ar,lang}:{en:string;ar:string;lang:Language}){return <>{lang==='ar'?ar:en}{lang==='both'&&<span className="arabic" dir="rtl">{ar}</span>}</>}
export function LanguageSwitch({lang,onChange}:{lang:Language;onChange:(v:Language)=>void}){return <div className="language" role="group" aria-label="Language / اللغة">{(['en','ar','both'] as Language[]).map((l,i)=><button key={l} className={lang===l?'active':''} aria-pressed={lang===l} onClick={()=>onChange(l)}>{['EN','العربية','EN / ع'][i]}</button>)}</div>}

/** Presenter account actions supplied by the VPS login shell (absent on Sites). */
/** EN / العربية switch for screens outside a workshop. The choice is remembered on this device. */
export function UiLanguageSwitch(){const lang=useUiLang();return <div className="language" role="group" aria-label="Language / اللغة">{([['en','EN'],['ar','العربية']] as [UiLang,string][]).map(([l,label])=><button key={l} lang={l} className={lang===l?'active':''} aria-pressed={lang===l} onClick={()=>setUiLang(l,true)}>{label}</button>)}</div>}

export const AccountContext=createContext<{signOut:()=>void}|null>(null);
export function SignOutButton({className='btn small ghost'}:{className?:string}){const account=useContext(AccountContext);const lang=useUiLang();if(!account)return null;return <button className={className} onClick={account.signOut}>{tx(lang,'Sign out','تسجيل الخروج')}</button>}

/* ---------- Dark / light templates ----------
   The preference is per browser: 'dark', 'light' or 'system' (follow the device).
   The resolved theme is written to <html data-theme>, which every stylesheet keys off.
   The inline script in index.html/layout.tsx applies it before first paint. */
export type ThemePreference='dark'|'light'|'system';
const THEME_KEY='ai-collab-theme';
const themeListeners=new Set<()=>void>();
const systemQuery=()=>typeof window!=='undefined'&&window.matchMedia?window.matchMedia('(prefers-color-scheme: light)'):null;
function readPreference():ThemePreference{try{const v=localStorage.getItem(THEME_KEY);if(v==='dark'||v==='light'||v==='system')return v}catch{}return 'system'}
function applyTheme(pref:ThemePreference){const resolved=pref==='system'?(systemQuery()?.matches?'light':'dark'):pref;const root=document.documentElement;root.dataset.theme=resolved;root.dataset.themePreference=pref;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',resolved==='light'?'#f4f5ef':'#101216');}
let fadeTimer:ReturnType<typeof setTimeout>|undefined;
export function setThemePreference(pref:ThemePreference){try{localStorage.setItem(THEME_KEY,pref)}catch{}const root=document.documentElement;root.classList.add('theme-fade');clearTimeout(fadeTimer);fadeTimer=setTimeout(()=>root.classList.remove('theme-fade'),400);applyTheme(pref);themeListeners.forEach(l=>l())}
function subscribeTheme(listener:()=>void){themeListeners.add(listener);const query=systemQuery();const onSystem=()=>{if(readPreference()==='system'){applyTheme('system');listener()}};const onStorage=(e:StorageEvent)=>{if(e.key===THEME_KEY){applyTheme(readPreference());listener()}};query?.addEventListener('change',onSystem);window.addEventListener('storage',onStorage);return()=>{themeListeners.delete(listener);query?.removeEventListener('change',onSystem);window.removeEventListener('storage',onStorage)}}
export function useThemePreference(){return useSyncExternalStore(subscribeTheme,readPreference,()=>'system' as ThemePreference)}
const themeOptions:[ThemePreference,string,string,typeof Sun][]=[['dark','Dark','داكن',Moon],['light','Light','فاتح',Sun],['system','Auto','تلقائي',Monitor]];
/** Segmented Dark / Light / Auto switch. Light is easier to read on projectors in bright rooms. */
export function ThemeSwitch(){const pref=useThemePreference();const lang=useUiLang();return <div className="theme-switch" role="radiogroup" aria-label={tx(lang,'Colour theme','مظهر الألوان')}>{themeOptions.map(([value,en,ar,Icon])=>{const label=tx(lang,en,ar);return <button key={value} type="button" role="radio" aria-checked={pref===value} className={pref===value?'active':''} title={value==='system'?tx(lang,'Auto — follow this device’s setting','تلقائي — يتبع إعداد هذا الجهاز'):tx(lang,en+' theme','المظهر ال'+ar)} aria-label={value==='system'?'Auto theme (follow device)':en+' theme'} onClick={()=>setThemePreference(value)}><Icon size={15}/><span className="theme-label">{label}</span></button>})}</div>}

export function TypeChip({type,lang}:{type:string;lang:Language}){const meta=typeMeta[type];const [en,ar]=meta?.label||[type,type];return <span className={'type-chip t-'+(meta?.tone||'idea')} title={meta?(lang==='ar'?meta.meaning[1]:meta.meaning[0]):undefined}>{lang==='ar'?ar:en}</span>}

const FOCUSABLE='button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLElement>(null);const close=useRef(onClose);useEffect(()=>{close.current=onClose});
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const first=ref.current?.querySelector<HTMLElement>('.modal-body '+FOCUSABLE)||ref.current?.querySelector<HTMLElement>(FOCUSABLE);first?.focus({preventScroll:true});
  // Only the top-most dialog reacts when dialogs are stacked (e.g. a room's details over the rooms manager).
  const keys=(e:KeyboardEvent)=>{const open=document.querySelectorAll('.modal');if(open[open.length-1]!==ref.current)return;if(e.key==='Escape'){e.stopPropagation();close.current();return}if(e.key!=='Tab'||!ref.current)return;const items=[...ref.current.querySelectorAll<HTMLElement>(FOCUSABLE)].filter(el=>el.offsetParent!==null);if(!items.length)return;const a=items[0],b=items[items.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus()}};
  document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);document.body.style.overflow=overflow;previous?.focus?.({preventScroll:true})}},[]);
 return <div className="modal-backdrop" onClick={onClose}><section ref={ref} className={'modal'+(wide?' modal-wide':'')} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{title}</h2><button className="btn small icon-btn secondary" aria-label={tx(getUiLang(),'Close dialog','إغلاق النافذة')} onClick={onClose}><X size={20}/></button></div><div className="modal-body">{children}</div></section></div>}

export function Timer({end}:{end:number|null}){const lang=useUiLang();const [now,setNow]=useState(Date.now());useEffect(()=>{if(!end)return;setNow(Date.now());const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[end]);if(!end)return null;const sec=Math.max(0,Math.ceil((end-now)/1000));return <span className={'timer'+(sec===0?' done':sec<=30?' urgent':'')} role="timer" aria-live="off"><Clock size={19}/> {String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}{sec===0&&<small> · {tx(lang,'Time’s up','انتهى الوقت')}</small>}</span>}
export function Empty({title,text}:{title?:string;text?:string}){const lang=useUiLang();title??=tx(lang,'The next great idea is on its way','الفكرة الرائعة التالية في الطريق');text??=tx(lang,'Student contributions will appear here as they arrive.','ستظهر مشاركات الطلاب هنا فور وصولها.');return <div className="empty"><span className="empty-icon"><Lightbulb size={26}/></span><h3>{title}</h3>{text}</div>}
export function download(filename:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
/** Clipboard API needs a secure context; fall back to a hidden textarea on plain-HTTP LAN previews. */
export async function copyText(text:string){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true}}catch{/* fall through */}try{const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();return ok}catch{return false}}
/** A single toast at a time; a new message restarts the timer instead of being cut short. */
export function useToast(){const [toast,setToast]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>()=>clearTimeout(timer.current),[]);const notify=useCallback((message:string)=>{clearTimeout(timer.current);setToast(message);timer.current=setTimeout(()=>setToast(''),3500)},[]);return {toast,notify};}
const MEDALS=['🥇','🥈','🥉'];
export function Results({data,reflection=false,lang}:{data:Snapshot;reflection?:boolean;lang?:Language}){const language=lang||data.config.language;const entries=reflection?Object.entries(data.reflection).sort((a,b)=>b[1]-a[1]):data.ideas.filter(i=>i.shortlisted&&i.status==='approved').sort((a,b)=>(b.votes||0)-(a.votes||0)).map(i=>[i.title,i.votes||0] as [string,number]);const max=Math.max(1,...entries.map(i=>i[1]));const total=entries.reduce((n,e)=>n+e[1],0);const unit=(n:number)=>language==='ar'?(reflection?'طالب':'صوت'):reflection?(n===1?'student':'students'):(n===1?'vote':'votes');
 return <div className="results">{entries.length?entries.map(([name,count],i)=><div className={'result'+(i===0&&count>0?' leader':'')} key={name+i}><div className="result-title"><strong><span className="result-rank">{count>0&&MEDALS[i]?MEDALS[i]:String(i+1).padStart(2,'0')}</span>{reflection&&language==='ar'?(skillArabic[skills.indexOf(name)]||name):name}</strong><span className="result-count">{count}<small>{total?Math.round(count/total*100):0}%</small></span></div><div className="bar-track"><div className="bar-fill" style={{width:count/max*100+'%',background:i===0?'var(--accent-fill)':i===1?'var(--purple)':'var(--teal)'}}/></div><small>{count} {unit(count)}</small></div>):<Empty title={language==='ar'?'بانتظار أول صوت':'Ready for the first vote'} text={language==='ar'?'ستتحدث النتائج مع تصويت الفريق.':'Results will update as the team votes.'}/>}</div>}
