"use client";
/* Visual views of team rooms: an illustrated floor plan, a status table, and a live room activity panel.
   Every view reads the same RoomSummary list, so the presenter, the projector and students see one picture. */
import {useRef,useState,type ReactNode} from 'react';
import {DoorOpen,Users,Lightbulb,MessageSquare,Vote,Hourglass,Eye,Crown,Map as MapIcon,LayoutGrid,List,Clock,Paperclip,Upload as UploadIcon,FileText,Trash2,Check,Download,Lock,Globe,Handshake,ShieldCheck} from 'lucide-react';
import {stages,stageArabic,type RoomSummary,type Language,type Snapshot,type Upload,type RoomVisibility} from './workshop';
import {useWorkshop,TypeChip,action,Modal} from './client';
import {appUrl} from './urls';
import {uid} from './id';
import {translateError,getUiLang} from './i18n';

export type RoomView='map'|'cards'|'list';
type L=(en:string,ar:string)=>string;
const translator=(lang:Language):L=>(en,ar)=>lang==='ar'?ar:en;
const roomNumber=(code:string)=>code.slice(code.lastIndexOf('-')+1);
/** A stable colour per name, so a person or room keeps its colour everywhere. */
export const hue=(name:string)=>[...name].reduce((n,ch)=>n*31+ch.charCodeAt(0)>>>0,7)%360;
const initials=(name:string)=>name.trim().split(/\s+/).map(w=>[...w][0]||'').join('').slice(0,2).toUpperCase()||'?';
/** Something was posted in the last three minutes. */
export const isLive=(r:RoomSummary)=>!!r.lastActivity&&Date.now()-r.lastActivity<180000&&!r.ended;
export type RoomState='active'|'recent'|'quiet'|'new'|'paused'|'ended';
/** The room's light: active (posted in the last 3 min), recently active (15 min), quiet, not started, paused or ended. */
export function roomState(r:RoomSummary):RoomState{if(r.ended)return 'ended';if(r.paused)return 'paused';if(!r.lastActivity)return 'new';const age=Date.now()-r.lastActivity;return age<180000?'active':age<900000?'recent':'quiet';}
const stateLabels:Record<RoomState,[string,string]>={active:['Active now','نشطة الآن'],recent:['Recently active','نشطة مؤخراً'],quiet:['Quiet','هادئة'],new:['Not started','لم تبدأ'],paused:['Paused','متوقفة'],ended:['Ended','انتهت']};
export function StatusLight({room,lang}:{room:RoomSummary;lang:Language}){const s=roomState(room);return <span className={'status-light s-'+s} title={timeAgo(room.lastActivity,lang)}><i aria-hidden="true"/>{translator(lang)(...stateLabels[s])}</span>}

export function timeAgo(ts:number|null,lang:Language){const t=translator(lang);if(!ts)return t('No activity yet','لا نشاط بعد');const s=Math.max(0,Math.round((Date.now()-ts)/1000));if(s<60)return t('just now','الآن');if(s<3600)return t(`${Math.floor(s/60)} min ago`,`قبل ${Math.floor(s/60)} د`);if(s<86400)return t(`${Math.floor(s/3600)} h ago`,`قبل ${Math.floor(s/3600)} س`);return new Date(ts).toLocaleDateString(lang==='ar'?'ar-OM-u-nu-latn':'en-GB',{day:'numeric',month:'short'});}
const stageName=(i:number,lang:Language)=>lang==='ar'?stageArabic[i]:stages[i];
const VIEW_KEY='ai-collab-room-view';
export function readView(fallback:RoomView):RoomView{try{const v=localStorage.getItem(VIEW_KEY);if(v==='map'||v==='cards'||v==='list')return v}catch{/* private mode */}return fallback}
export function saveView(v:RoomView){try{localStorage.setItem(VIEW_KEY,v)}catch{/* private mode */}}

export function ViewSwitch({view,onChange,lang,list=true}:{view:RoomView;onChange:(v:RoomView)=>void;lang:Language;list?:boolean}){const t=translator(lang);const options:[RoomView,string,string,typeof MapIcon][]=[['map','Map','خريطة',MapIcon],['cards','Cards','بطاقات',LayoutGrid],...(list?[['list','List','قائمة',List] as [RoomView,string,string,typeof MapIcon]]:[])];
 return <div className="tabs segmented view-switch" role="group" aria-label={t('Rooms view','عرض الغرف')}>{options.map(([v,en,ar,Icon])=><button key={v} type="button" className={view===v?'active':''} aria-pressed={view===v} onClick={()=>onChange(v)}><Icon size={14}/>{t(en,ar)}</button>)}</div>}

/** Status chips for one room: who is there and what has happened. */
export function RoomStats({room,lang,large=false}:{room:RoomSummary;lang:Language;large?:boolean}){const t=translator(lang);
 const items:[typeof Users,number,string,string,string][]=[[Users,room.members,'members','أعضاء','Members in this team'],[Eye,room.guests,'visitors','زوار','Visitors from other teams'],[Lightbulb,room.ideas,'contributions','مشاركات','Ideas, solutions and improvements'],[MessageSquare,room.comments,'messages','رسائل','Comments in the discussion'],[Vote,room.ideaVotes,'votes','أصوات','Votes on ideas in this room'],[Paperclip,room.uploads,'files','ملفات','Files shared in this room']];
 return <div className={'room-stats'+(large?' large':'')}>{items.map(([Icon,n,en,ar,title])=><span key={en} title={title}><Icon size={large?18:14}/><strong>{n}</strong>{t(n===1?en.replace(/s$/,''):en,ar)}</span>)}{room.pending>0&&<span className="pending" title={t('Waiting for approval','بانتظار الموافقة')}><Hourglass size={large?18:14}/><strong>{room.pending}</strong>{t('pending','قيد المراجعة')}</span>}</div>}

/** The nine steps as a small progress track. */
export function StageTrack({stage,lang}:{stage:number;lang:Language}){return <span className="stage-track" title={`${stage+1}. ${stageName(stage,lang)}`} aria-label={`${stage+1} / 9 · ${stageName(stage,lang)}`}>{stages.map((s,i)=><i key={s} className={i<stage?'done':i===stage?'now':''}/>)}</span>}

/** Illustrated floor plan: each team is a room with its people inside, a desk of activity, and a door to open it. */
export function RoomsMap({rooms,lang,title,onOpen,mine=null,large=false}:{rooms:RoomSummary[];lang:Language;title:string;onOpen?:(r:RoomSummary)=>void;mine?:string|null;large?:boolean}){const t=translator(lang);
 const total=(k:'members'|'guests'|'ideas'|'comments')=>rooms.reduce((n,r)=>n+r[k],0);
 return <div className={'rooms-map'+(large?' large':'')}>
  <div className="map-hall"><span className="map-hall-name"><DoorOpen size={large?24:18}/>{title}</span><span className="map-hall-stats"><span><strong>{rooms.length}</strong> {t('rooms','غرف')}</span><span><strong>{total('members')}</strong> {t('members','أعضاء')}</span><span><strong>{total('guests')}</strong> {t('visitors','زوار')}</span><span><strong>{total('ideas')}</strong> {t('contributions','مشاركات')}</span><span><strong>{total('comments')}</strong> {t('messages','رسائل')}</span></span></div>
  <div className="map-floor">{rooms.map(r=>{const live=isLive(r);const more=Math.max(0,r.members-r.people.length);const Tag=onOpen?'button':'div';
   return <Tag key={r.code} {...(onOpen?{type:'button' as const,onClick:()=>onOpen(r),'aria-label':t(`Open ${r.name}`,`افتح ${r.name}`)}:{})} className={'map-room'+(live?' live':'')+(r.code===mine?' mine':'')+(r.ended?' ended':'')+(r.paused?' paused':'')} style={{'--room-hue':hue(r.name)} as React.CSSProperties}>
    <span className="map-room-roof"><span className="map-room-no" dir="ltr">{roomNumber(r.code)}</span><strong>{r.name}</strong>{r.visibility!=='open'&&(r.visibility==='private'?<Lock size={13}/>:<Handshake size={13}/>)}<StatusLight room={r} lang={lang}/></span>
    <span className="map-room-topic">{r.challenge}</span>
    <span className="map-room-floor">{r.people.map((p,i)=><span key={p.name+i} className={'map-person'+(p.lead?' lead':'')} title={p.name+(p.lead?' · '+t('room lead','قائد الغرفة'):'')} style={{'--avatar-hue':hue(p.name)} as React.CSSProperties}>{initials(p.name)}{p.lead&&<Crown size={11}/>}</span>)}{more>0&&<span className="map-person more">+{more}</span>}{r.guests>0&&<span className="map-visitors" title={t('Visitors','الزوار')}><Eye size={13}/>{r.guests}</span>}{!r.members&&<span className="map-empty">{t('Empty — waiting for its team','فارغة — بانتظار فريقها')}</span>}</span>
    <span className="map-room-desk"><span title={t('Contributions','المشاركات')}><Lightbulb size={14}/>{r.ideas}</span><span title={t('Messages','الرسائل')}><MessageSquare size={14}/>{r.comments}</span><span title={t('Votes','الأصوات')}><Vote size={14}/>{r.ideaVotes}</span>{r.uploads>0&&<span title={t('Files','الملفات')}><Paperclip size={14}/>{r.uploads}</span>}{r.pending>0&&<span className="pending" title={t('Pending approval','بانتظار الموافقة')}><Hourglass size={14}/>{r.pending}</span>}</span>
    <StageTrack stage={r.stage} lang={lang}/>
    <span className="map-room-foot"><span>{r.stage+1}. {stageName(r.stage,lang)}</span><span><Clock size={12}/>{r.ended?t('Ended','انتهت'):r.paused?t('Paused','متوقفة'):timeAgo(r.lastActivity,lang)}</span></span>
   </Tag>})}</div>
 </div>}

const visibilityText:Record<RoomVisibility,[string,string,string,string]>={open:['All teams','كل الفرق','Any team can visit, read and comment.','يمكن لأي فريق الزيارة والقراءة والتعليق.'],partners:['Selected teams','فرق مختارة','Only the teams you choose can visit and comment.','فقط الفرق التي تختارها يمكنها الزيارة والتعليق.'],private:['Only our team','فريقنا فقط','Other teams cannot see inside. The presenter always can.','لا ترى الفرق الأخرى ما بداخل الغرفة. ويمكن لمقدم الورشة دائماً رؤيتها.']};
const visibilityIcon={open:Globe,partners:Handshake,private:Lock};
/** Small badge: who can see inside this room. Nothing is shown for open rooms. */
export function VisibilityBadge({room,lang,team}:{room:RoomSummary;lang:Language;team?:string|null}){const t=translator(lang);if(room.visibility==='open')return null;const invited=room.visibility==='partners'&&!!team&&team!==room.code&&room.partners.includes(team);const Icon=visibilityIcon[room.visibility];return <span className={'visibility-badge v-'+room.visibility+(invited?' invited':'')} title={t(visibilityText[room.visibility][2],visibilityText[room.visibility][3])}><Icon size={12}/>{invited?t('Invited your team','دعت فريقك'):room.visibility==='private'?t('Private','خاصة'):t('Selected teams','فرق مختارة')}</span>}

/** Who can see a room's discussion: every team, chosen partner teams, or only the room's own team. */
export function PrivacyEditor({visibility,partners,others,lang,busy,save,heading=true}:{visibility:RoomVisibility;partners:string[];others:RoomSummary[];lang:Language;busy:boolean;heading?:boolean;save:(patch:{visibility?:RoomVisibility;partners?:string[]})=>void}){const t=translator(lang);
 const toggle=(code:string)=>save({visibility:'partners',partners:partners.includes(code)?partners.filter(c=>c!==code):[...partners,code]});
 return <section className="privacy-editor">{heading&&<h3><ShieldCheck size={16}/>{t('Who can see this room’s discussion?','من يمكنه رؤية نقاش هذه الغرفة؟')}</h3>}
  <div className="privacy-options" role="radiogroup" aria-label={t('Room visibility','ظهور الغرفة')}>{(['open','partners','private'] as RoomVisibility[]).map(v=>{const Icon=visibilityIcon[v];const [en,ar,hen,har]=visibilityText[v];return <button key={v} type="button" role="radio" aria-checked={visibility===v} className={'privacy-option v-'+v+(visibility===v?' active':'')} disabled={busy} onClick={()=>visibility!==v&&save({visibility:v})}><Icon size={18}/><strong>{t(en,ar)}</strong><small>{t(hen,har)}</small></button>})}</div>
  {visibility==='partners'&&<div className="partner-pick"><p className="nav-label">{t('Teams allowed to visit and discuss with us','الفرق المسموح لها بالزيارة والنقاش معنا')}</p>{others.length?<div className="partner-list">{others.map(r=><label key={r.code} className={'partner-chip'+(partners.includes(r.code)?' on':'')} style={{'--room-hue':hue(r.name)} as React.CSSProperties}><input type="checkbox" checked={partners.includes(r.code)} disabled={busy} onChange={()=>toggle(r.code)}/><span className="room-dot"/>{r.name}</label>)}</div>:<p className="muted">{t('There are no other teams yet.','لا توجد فرق أخرى بعد.')}</p>}{!partners.length&&others.length>0&&<p className="inline-help">{t('No team is selected yet, so the room is private for now.','لم يُختر أي فريق بعد، لذا فالغرفة خاصة حالياً.')}</p>}</div>}
 </section>}

/** A team room drawn as a room: coloured roof, status light, its people, the latest message, counters and progress. */
export function RoomCard({room,lang,mine=false,handle,dragging=false,team,children}:{room:RoomSummary;lang:Language;mine?:boolean;handle?:ReactNode;dragging?:boolean;team?:string|null;children?:ReactNode}){const t=translator(lang);const s=roomState(room);const more=Math.max(0,room.members-room.people.length);
 return <article data-room={room.code} className={'room-card s-'+s+(mine?' mine':'')+(dragging?' dragging':'')} style={{'--room-hue':hue(room.name)} as React.CSSProperties}>
  <div className="room-card-roof">{handle}<span className="map-room-no" dir="ltr">{roomNumber(room.code)}</span><h3 title={room.name}>{room.name}</h3><VisibilityBadge room={room} lang={lang} team={team}/><StatusLight room={room} lang={lang}/></div>
  <div className="room-card-body">
   <p className="room-card-topic">{room.challenge}</p>
   <div className="room-card-people">{room.people.map((p,i)=><span key={p.name+i} className={'map-person'+(p.lead?' lead':'')} title={p.name+(p.lead?' · '+t('room lead','قائد الغرفة'):'')} style={{'--avatar-hue':hue(p.name)} as React.CSSProperties}>{initials(p.name)}{p.lead&&<Crown size={11}/>}</span>)}{more>0&&<span className="map-person more">+{more}</span>}{room.guests>0&&<span className="map-visitors" title={t('Visitors','الزوار')}><Eye size={13}/>{room.guests}</span>}{!room.members&&<span className="map-empty">{t('Empty — waiting for its team','فارغة — بانتظار فريقها')}</span>}{mine&&<span className="pill lime your-team">{t('Your team','فريقك')}</span>}</div>
   <div className={'room-card-discussion'+(room.latest?'':' none')}>{room.canVisit?<MessageSquare size={15}/>:<Lock size={15}/>}{!room.canVisit?<span>{t('The discussion is private to this team.','النقاش خاص بهذا الفريق.')}</span>:room.latest?<span><strong>{room.latest.nickname}</strong> “{room.latest.text}”</span>:<span>{t('No discussion yet','لا نقاش بعد')}</span>}{room.recent>0&&<span className="heat" title={t('Posts in the last 10 minutes','مشاركات آخر 10 دقائق')}>+{room.recent}</span>}</div>
   <RoomStats room={room} lang={lang}/>
   <div className="room-card-progress"><StageTrack stage={room.stage} lang={lang}/><span>{room.stage+1}. {stageName(room.stage,lang)}</span><span><Clock size={12}/>{timeAgo(room.lastActivity,lang)}</span></div>
  </div>
  {children&&<div className="room-card-actions">{children}</div>}
 </article>}

/** Status table: one row per room, sortable from the toolbar above it. */
export function RoomsList({rooms,lang,onOpen,handle,dragging}:{rooms:RoomSummary[];lang:Language;onOpen:(r:RoomSummary)=>void;handle?:(r:RoomSummary)=>ReactNode;dragging?:string}){const t=translator(lang);
 return <div className="rooms-table-wrap"><table className="table rooms-table"><thead><tr>{handle&&<th aria-label={t('Order','الترتيب')}/>}<th>{t('Room','الغرفة')}</th><th>{t('Status','الحالة')}</th><th>{t('Step','الخطوة')}</th><th title={t('Members','الأعضاء')}><Users size={14}/></th><th title={t('Visitors','الزوار')}><Eye size={14}/></th><th title={t('Contributions','المشاركات')}><Lightbulb size={14}/></th><th title={t('Messages','الرسائل')}><MessageSquare size={14}/></th><th title={t('Votes','الأصوات')}><Vote size={14}/></th><th title={t('Files','الملفات')}><Paperclip size={14}/></th><th title={t('Pending','قيد المراجعة')}><Hourglass size={14}/></th><th>{t('Last activity','آخر نشاط')}</th></tr></thead>
  <tbody>{rooms.map(r=><tr key={r.code} data-room={r.code} onClick={()=>onOpen(r)} className={(isLive(r)?'live':'')+(dragging===r.code?' dragging':'')}>{handle&&<td onClick={e=>e.stopPropagation()}>{handle(r)}</td>}<td><button type="button" className="link-button" onClick={e=>{e.stopPropagation();onOpen(r)}}><span className="room-dot" style={{'--room-hue':hue(r.name)} as React.CSSProperties}/><strong>{r.name}</strong> <span className="muted" dir="ltr">{roomNumber(r.code)}</span></button><small className="muted">{r.challenge}</small></td><td><StatusLight room={r} lang={lang}/></td><td><StageTrack stage={r.stage} lang={lang}/><small>{r.stage+1}. {stageName(r.stage,lang)}</small></td><td className="num">{r.members}</td><td className="num">{r.guests}</td><td className="num">{r.ideas}</td><td className="num">{r.comments}</td><td className="num">{r.ideaVotes}</td><td className="num">{r.uploads}</td><td className={'num'+(r.pending?' pending':'')}>{r.pending}</td><td>{isLive(r)&&<span className="live-dot"/>} {timeAgo(r.lastActivity,lang)}</td></tr>)}</tbody></table></div>}

/** Live view inside one room: its people and everything posted, newest first. Presenter only. */
export function RoomActivity({code,lang}:{code:string;lang:Language}){const t=translator(lang);const {data,error,refresh}=useWorkshop(code);
 if(!data)return <p className="connecting">{error||<><span className="spinner"/>{t('Opening room…','جارٍ فتح الغرفة…')}</>}</p>;
 const people=data.people||[];const manage=async(participant:string,op:'remove'|'lead')=>{try{await action({action:'member',code,participant,op});await refresh()}catch(e){window.alert((e as Error).message)}};const groups:[string,string,string][]=[['lead','Room lead','قائد الغرفة'],['member','Members','الأعضاء'],['guest','Visitors','الزوار']];
 const feed=[...data.ideas.filter(i=>i.status!=='deleted').map(i=>({...i,file:null as Upload|null})),...(data.uploads||[]).map(f=>({id:f.id,nickname:f.nickname,type:'file',status:f.status,created:f.created,title:f.name,text:'',parent:null,shortlisted:0,votes:null,file:f}))].sort((a,b)=>b.created-a.created).slice(0,50);const title=(id:string|null)=>data.ideas.find(i=>i.id===id)?.title||'';
 return <div className="room-activity">
  <section className="room-people"><h3><Users size={16}/>{t('People','الأشخاص')} <span className="count-badge">{people.length}</span></h3>{people.length?groups.map(([role,en,ar])=>{const list=people.filter(p=>p.role===role);return list.length?<div key={role}><p className="nav-label">{t(en,ar)} · {list.length}</p><ul>{list.map((p,i)=><li key={p.id||p.nickname+i}><span className={'map-person small'+(role==='guest'?' guest':'')} style={{'--avatar-hue':hue(p.nickname)} as React.CSSProperties}>{initials(p.nickname)}</span><span>{p.nickname}</span>{role==='lead'&&<Crown size={13}/>}<small className="muted">{timeAgo(p.created,lang)}</small>{role==='member'&&<span className="person-actions"><button type="button" className="btn small ghost icon-btn" title={t('Make lead','اجعله القائد')} aria-label={t('Make lead','اجعله القائد')} onClick={()=>void manage(p.id,'lead')}><Crown size={13}/></button><button type="button" className="btn small ghost icon-btn" title={t('Remove from team','إزالة من الفريق')} aria-label={t('Remove from team','إزالة من الفريق')} onClick={()=>void manage(p.id,'remove')}><Trash2 size={13}/></button></span>}</li>)}</ul></div>:null}):<p className="muted">{t('Nobody has joined yet.','لم ينضم أحد بعد.')}</p>}</section>
  <section className="room-feed"><h3><MessageSquare size={16}/>{t('Activity','النشاط')} <span className="count-badge">{feed.length}</span></h3>{feed.length?<ol>{feed.map(i=><li key={i.id} className={i.type==='comment'?'is-comment':''}><span className="map-person small" style={{'--avatar-hue':hue(i.nickname)} as React.CSSProperties}>{initials(i.nickname)}</span><div><div className="feed-top"><strong>{i.nickname}</strong>{i.file?<span className="type-chip t-file"><Paperclip size={11}/> {t('File','ملف')}</span>:<TypeChip type={i.type} lang={lang}/>}{i.status==='pending'&&<span className="pill status-pending">{t('Pending','قيد المراجعة')}</span>}{i.status==='hidden'&&<span className="pill">{t('Hidden','مخفية')}</span>}{!!i.shortlisted&&<span className="pill lime">★ {t('Finalist','مرشح')}</span>}<time>{timeAgo(i.created,lang)}</time></div>{i.file?<FileLink file={i.file}/>:i.type==='comment'?<p className="feed-parent">↳ {t('on','على')} “{title(i.parent)}”</p>:<p className="feed-title">{i.title}</p>}{!i.file&&<p className="feed-text">{i.text}</p>}{i.type!=='comment'&&!i.file&&typeof i.votes==='number'&&i.votes>0&&<small className="muted"><Vote size={12}/> {i.votes}</small>}</div></li>)}</ol>:<p className="muted">{t('Nothing posted yet. Contributions and messages appear here live.','لم يُنشر شيء بعد. تظهر المشاركات والرسائل هنا مباشرة.')}</p>}</section>
  <div className="room-activity-files"><RoomFiles data={data} lang={lang} refresh={refresh} canUpload manage/></div>
 </div>}

/* ---------- Files shared in a room ---------- */
const CHUNK=96*1024,MAX_FILE=3*1024*1024;
export const fileUrl=(id:string,download=false)=>appUrl('/api/upload?id=')+id+(download?'&download=1':'');
const fileSize=(n:number)=>n<1024*1024?Math.max(1,Math.round(n/1024))+' KB':(n/1024/1024).toFixed(1)+' MB';
/** Large photos are resized on the device before sending, which keeps uploads quick on campus Wi-Fi. */
async function shrink(file:File):Promise<Blob>{if(!/^image\/(jpeg|png|webp)$/.test(file.type)||typeof createImageBitmap!=='function')return file;try{const bmp=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bmp.width,bmp.height));if(scale===1&&file.size<=900*1024){bmp.close();return file}const c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);const g=c.getContext('2d');if(!g){bmp.close();return file}g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(bmp,0,0,c.width,c.height);bmp.close();const out=await new Promise<Blob|null>(r=>c.toBlob(r,'image/jpeg',0.85));return out&&out.size<file.size?out:file}catch{return file}}
/** Sends a file in pieces small enough for the server's proxy; retries a piece twice on a network error. */
export async function sendFile(code:string,file:File,onProgress?:(share:number)=>void){const blob=await shrink(file);if(blob.size>MAX_FILE)throw new Error(translateError('The file is too large (3 MB at most).',getUiLang()));const id=uid(),total=Math.max(1,Math.ceil(blob.size/CHUNK));const name=blob===file?file.name:file.name.replace(/\.[^.]+$/,'')+'.jpg';
 for(let i=0;i<total;i++){for(let tries=0;;tries++){let r:Response;try{r=await fetch(appUrl('/api/upload')+`?code=${encodeURIComponent(code)}&id=${id}&index=${i}&total=${total}`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(name)},body:blob.slice(i*CHUNK,(i+1)*CHUNK)})}catch{if(tries<2)continue;throw new Error(translateError('Unable to save the file right now. Please retry.',getUiLang()))}const d=await r.json().catch(()=>({})) as {error?:string;status?:string};if(!r.ok){if(r.status>=500&&tries<2)continue;throw new Error(translateError(d.error||'Unable to save the file right now. Please retry.',getUiLang()))}onProgress?.((i+1)/total);if(i===total-1)return d;break}}}

function FileLink({file}:{file:Upload}){return file.type.startsWith('image/')?<a className="feed-file" href={fileUrl(file.id)} target="_blank" rel="noreferrer"><img src={fileUrl(file.id)} alt={file.name} loading="lazy"/><span>{file.name}</span></a>:<a className="feed-file" href={fileUrl(file.id,true)}><FileText size={22}/><span>{file.name} · {fileSize(file.size)}</span></a>}

/** A room's shared files: upload (members and facilitators), preview images, download, approve or remove. */
export function RoomFiles({data,lang,refresh,canUpload,manage}:{data:Snapshot;lang:Language;refresh:()=>Promise<void>;canUpload:boolean;manage:boolean}){const t=translator(lang);const files=data.uploads||[];
 const input=useRef<HTMLInputElement>(null);const [progress,setProgress]=useState<number|null>(null),[error,setError]=useState(''),[note,setNote]=useState(''),[preview,setPreview]=useState<Upload|null>(null),[removing,setRemoving]=useState(''),[busy,setBusy]=useState(false);
 async function pick(list:FileList|null){if(!list?.length)return;setError('');setNote('');const all=[...list];let pending=0;try{for(let n=0;n<all.length;n++){setProgress(n/all.length);const r=await sendFile(data.code,all[n],share=>setProgress((n+share)/all.length));if(r?.status==='pending')pending++;}setNote(pending?t('Shared — waiting for approval before others see it.','تمت المشاركة — بانتظار الموافقة قبل أن يراها الآخرون.'):t('File shared with the room ✓','تمت مشاركة الملف مع الغرفة ✓'))}catch(e){setError((e as Error).message)}finally{setProgress(null);if(input.current)input.current.value='';await refresh()}}
 async function moderate(f:Upload,op:'delete'|'approve'){setBusy(true);setError('');try{await action({action:'file',code:data.code,id:f.id,op});setRemoving('');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="room-files">
  <div className="room-files-head"><h3><Paperclip size={16}/>{t('Files','الملفات')} <span className="count-badge">{files.length}</span></h3>{canUpload&&<><input ref={input} type="file" hidden multiple accept="image/png,image/jpeg,image/gif,image/webp,application/pdf" onChange={e=>void pick(e.target.files)}/><button className="btn small primary" disabled={progress!==null} onClick={()=>input.current?.click()}><UploadIcon size={15}/>{progress!==null?t('Uploading…','جارٍ الرفع…'):t('Share a file','شارك ملفاً')}</button></>}</div>
  {progress!==null&&<div className="upload-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress*100)}><span style={{width:Math.max(4,progress*100)+'%'}}/></div>}
  {canUpload&&<p className="inline-help">{t('Photos, sketches, screenshots or PDFs — 3 MB at most. Please do not share personal or sensitive information.','صور أو رسومات أو لقطات شاشة أو ملفات PDF — بحد أقصى 3 ميغابايت. يرجى عدم مشاركة معلومات شخصية أو حساسة.')}</p>}
  {note&&<div className="success" role="status">{note}</div>}{error&&<div className="error" role="alert">{error}</div>}
  {files.length?<div className="file-grid">{files.map(f=><article key={f.id} className={'file-card'+(f.status==='pending'?' pending':'')}>
   {f.type.startsWith('image/')?<button type="button" className="file-thumb" onClick={()=>setPreview(f)} aria-label={t('Preview ','معاينة ')+f.name}><img src={fileUrl(f.id)} alt={f.name} loading="lazy"/></button>:<a className="file-thumb pdf" href={fileUrl(f.id,true)} aria-label={t('Download ','تنزيل ')+f.name}><FileText size={34}/><span>PDF</span></a>}
   <div className="file-info"><strong title={f.name}>{f.name}</strong><small>{f.nickname} · {timeAgo(f.created,lang)} · {fileSize(f.size)}</small>{f.status==='pending'&&<span className="pill status-pending">{t('Waiting for approval','بانتظار الموافقة')}</span>}</div>
   <div className="file-actions">{removing===f.id?<><button className="btn small danger" disabled={busy} onClick={()=>void moderate(f,'delete')}>{t('Remove','إزالة')}</button><button className="btn small secondary" onClick={()=>setRemoving('')}>{t('Keep','إبقاء')}</button></>:<><a className="btn small ghost icon-btn" href={fileUrl(f.id,true)} aria-label={t('Download','تنزيل')} title={t('Download','تنزيل')}><Download size={14}/></a>{manage&&f.status==='pending'&&<button className="btn small primary" disabled={busy} onClick={()=>void moderate(f,'approve')}><Check size={14}/>{t('Approve','موافقة')}</button>}{(manage||f.mine)&&<button className="btn small ghost icon-btn" aria-label={t('Remove file','إزالة الملف')} title={t('Remove file','إزالة الملف')} onClick={()=>setRemoving(f.id)}><Trash2 size={14}/></button>}</>}</div>
  </article>)}</div>:<div className="empty file-empty"><span className="empty-icon"><Paperclip size={24}/></span>{canUpload?t('No files yet. Share a photo of your sketch, a screenshot or a PDF with your team.','لا توجد ملفات بعد. شارك صورة لرسمتك أو لقطة شاشة أو ملف PDF مع فريقك.'):t('No files shared in this room yet.','لم تُشارك ملفات في هذه الغرفة بعد.')}</div>}
  {preview&&<Modal wide title={preview.name} onClose={()=>setPreview(null)}><img className="file-preview" src={fileUrl(preview.id)} alt={preview.name}/><p className="muted">{preview.nickname} · {timeAgo(preview.created,lang)} · <a href={fileUrl(preview.id,true)}>{t('Download','تنزيل')}</a></p></Modal>}
 </section>}

