"use client";
import type {Config} from './workshop';
const toggles=[
 ['anonymous','Allow anonymous participation / السماح بالمشاركة دون اسم','Lowers the barrier for shy students. Nicknames are optional.'],
 ['moderated','Approve submissions before public display / مراجعة المشاركات قبل عرضها','Recommended for large or public rooms. You approve each idea before others see it.'],
 ['liveResults','Show voting results live / عرض نتائج التصويت مباشرة','Live results build energy; hidden results reduce bandwagon voting.'],
 ['multiple','Allow multiple submissions (up to 20 per stage) / السماح بمشاركات متعددة','More ideas per person. Turn off to encourage one carefully written contribution.'],
] as const;
export function Settings({value,onChange}:{value:Config;onChange:(v:Config)=>void}){const update=(patch:Partial<Config>)=>onChange({...value,...patch});return <div className="form-grid"><div className="field"><label htmlFor="workshop-name">Workshop name / اسم الورشة</label><input id="workshop-name" value={value.name} maxLength={100} required onChange={e=>update({name:e.target.value})}/></div><div className="field"><label htmlFor="challenge-name">Challenge name / اسم التحدي</label><input id="challenge-name" value={value.challenge} maxLength={100} required onChange={e=>update({challenge:e.target.value})}/></div><div className="field full"><label htmlFor="challenge-question">Challenge question / سؤال التحدي</label><textarea id="challenge-question" value={value.question} maxLength={1000} required placeholder="How can we use technology and AI to…" onChange={e=>update({question:e.target.value})}/><small className="inline-help">A good challenge question names who it is for and leaves room for many answers. Start with “How can we…”.</small></div><div className="field full"><label htmlFor="description">Description / الوصف</label><input id="description" value={value.description} maxLength={1000} onChange={e=>update({description:e.target.value})}/></div><div className="field"><label htmlFor="language">Workshop language / لغة الورشة</label><select id="language" value={value.language} onChange={e=>update({language:e.target.value as Config['language']})}><option value="en">English</option><option value="ar">العربية</option><option value="both">Bilingual / ثنائي اللغة</option></select></div><div className="field"><label htmlFor="max-votes">Votes per student / أصوات لكل طالب</label><select id="max-votes" value={value.maxVotes} onChange={e=>update({maxVotes:Number(e.target.value)})}>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n} value={n}>{n} {n===1?'vote':'votes'}</option>)}</select></div><div className="field full toggle-list">{toggles.map(([key,label,help])=><label key={key} className="toggle-row"><input type="checkbox" role="switch" checked={value[key]} onChange={e=>update({[key]:e.target.checked})}/><span className="toggle-text"><strong>{label}</strong><small>{help}</small></span></label>)}</div></div>}
