"use client";
/* Team rooms: each room is a small workshop of its own, linked to the main workshop.
   Teams develop their own project through the same stages, can visit other rooms as guests,
   and the presenter follows every room from one overview. */
import {useState,type ReactNode} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {DoorOpen,Users,Lightbulb,Plus,Copy,Monitor,ExternalLink,Trash2,Megaphone,ArrowLeft,Eye,UserPlus,Crown,Pause,Play,ArrowRight,Share2,Pencil,Search,Trophy,Vote,ChevronLeft,ChevronRight,Check} from 'lucide-react';
import {stages,stageArabic,type Snapshot,type RoomSummary,type Language,type Config} from './workshop';
import {action,Modal,copyText,useWorkshop,useToast} from './client';
import {appUrl} from './urls';
import {RoomsMap,RoomsList,RoomStats,StageTrack,RoomActivity,ViewSwitch,readView,saveView,timeAgo,isLive,type RoomView} from './rooms-visual';

type L=(en:string,ar:string)=>string;
const translator=(lang:Language):L=>(en,ar)=>lang==='ar'?ar:en;
const joinLink=(code:string)=>(typeof location!=='undefined'?location.origin:'')+appUrl('/join?code=')+code;
const goTo=(code:string)=>{location.href=appUrl('/join?code=')+code};
const roomNumber=(code:string)=>code.slice(code.lastIndexOf('-')+1);

/** A message from the presenter shown in the main workshop and every room. */
export function Broadcast({text,lang}:{text?:string;lang:Language}){if(!text)return null;const t=translator(lang);return <div className="broadcast" role="status"><Megaphone size={18}/><span><strong>{t('From the presenter','من مقدم الورشة')}</strong>{text}</span></div>}

export function RoomTile({room,lang,mine=false,children}:{room:RoomSummary;lang:Language;mine?:boolean;children?:ReactNode}){const t=translator(lang);
 return <article className={'room-tile'+(mine?' mine':'')}>
  <div className="room-tile-top"><span className="room-name"><DoorOpen size={17}/>{room.name}</span><span className="pill" dir="ltr">{roomNumber(room.code)}</span></div>
  <p className="room-focus">{room.challenge}</p>
  <RoomStats room={room} lang={lang}/>
  <div className="room-meta"><span className="pill lime">{room.stage+1}. {t(stages[room.stage],stageArabic[room.stage])}</span>{isLive(room)&&<span className="live-dot" title={t('Active now','نشطة الآن')}/>}<span className="muted">{timeAgo(room.lastActivity,lang)}</span>{room.paused&&<span className="pill">{t('Paused','متوقفة')}</span>}{room.ended&&<span className="pill">{t('Ended','انتهت')}</span>}{mine&&<span className="pill lime">{t('Your team','فريقك')}</span>}</div>
  {children&&<div className="room-actions">{children}</div>}
 </article>}

/** Projector screen: every team's progress at a glance. */
export function RoomsBoard({data,lang}:{data:Snapshot;lang:Language}){const t=translator(lang);const rooms=data.rooms||[];
 return <><div className="section-heading"><h1>{t('Our team rooms','غرف فرقنا')}</h1><span className="muted">{rooms.length} {t('teams','فرق')} · {rooms.reduce((n,r)=>n+r.members,0)} {t('members','عضو')} · {rooms.reduce((n,r)=>n+r.ideas,0)} {t('ideas','فكرة')}</span></div>
  <Broadcast text={data.config.broadcast} lang={lang}/>
  {rooms.length?<RoomsMap rooms={rooms} lang={lang} title={data.config.name} large/>:<p className="subtitle">{t('Team rooms will appear here.','ستظهر غرف الفرق هنا.')}</p>}
  <p className="muted" style={{marginTop:24,textAlign:'center'}}>{t('Join the workshop, then open the Team rooms tab to find your team.','انضم إلى الورشة، ثم افتح تبويب غرف الفرق لتجد فريقك.')}</p></>}

/** Presenter overview: create rooms, guide every room at once, and open any room. */
export function RoomsPanel({data,lang,busy,run,control,present,notify,reload}:{data:Snapshot;lang:Language;busy:boolean;run:(body:Record<string,unknown>,success?:string)=>Promise<boolean>;control:(patch:Partial<Config>)=>Promise<boolean>;present:()=>void;notify:(m:string)=>void;reload:()=>Promise<void>}){
 const t=translator(lang);const c=data.config;const rooms=data.rooms||[];
 const [name,setName]=useState(''),[focus,setFocus]=useState(''),[count,setCount]=useState(4),[stage,setStage]=useState(2),[draft,setDraft]=useState<string|null>(null);
 // The message box shows what every room sees until the presenter starts typing.
 const message=draft??(c.broadcast||''),setMessage=setDraft;
 const teamName=(n:number)=>t(`Team ${n}`,`الفريق ${n}`);
 if(!c.teamRooms&&!rooms.length)return <div className="stack">
  <p>{t('Split the audience into team rooms. Each team develops its own project through the same steps — ideas, improvements, voting and a project brief — while this main workshop stays the shared space for the whole class.','قسّم الحضور إلى غرف فرق. يطوّر كل فريق مشروعه الخاص بالخطوات نفسها — الأفكار والتحسين والتصويت وملخص المشروع — وتبقى هذه الورشة الرئيسية مساحة مشتركة للجميع.')}</p>
  <ul className="room-explain"><li>{t('Students join a team from the Team rooms tab, or with the room’s own link or QR code.','ينضم الطلاب إلى فريق من تبويب غرف الفرق، أو برابط الغرفة أو رمز QR الخاص بها.')}</li><li>{t('The first member leads the room and can move it through the steps. You can open and guide any room.','أول عضو يقود الغرفة ويمكنه نقلها بين الخطوات، ويمكنك فتح أي غرفة وتوجيهها.')}</li><li>{t('Students can visit other rooms as guests to read and comment — great for peer feedback.','يمكن للطلاب زيارة غرف أخرى كضيوف للقراءة والتعليق — مفيد للتغذية الراجعة بين الزملاء.')}</li></ul>
  <button className="btn primary" disabled={busy} onClick={()=>void control({teamRooms:true})}><DoorOpen size={17}/>{t('Turn on team rooms','تفعيل غرف الفرق')}</button></div>;
 return <div className="stack rooms-panel">
  <section className="rooms-section"><h3>{t('Create rooms','إنشاء الغرف')}</h3>
   <div className="actions"><label className="inline-field">{t('Quick start','بداية سريعة')}<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[2,3,4,5,6,8,10,12].map(n=><option key={n} value={n}>{n} {t('teams','فرق')}</option>)}</select></label><button className="btn secondary" disabled={busy} onClick={()=>void run({action:'createRoom',names:Array.from({length:count},(_,i)=>teamName(rooms.length+i+1))},t(`${count} rooms created`,`تم إنشاء ${count} غرف`))}><Plus size={16}/>{t('Create teams','إنشاء الفرق')}</button></div>
   <form className="room-create" onSubmit={e=>{e.preventDefault();void run({action:'createRoom',name,challenge:focus},t('Room created','تم إنشاء الغرفة')).then(ok=>{if(ok){setName('');setFocus('')}})}}><input value={name} maxLength={60} required placeholder={t('Room name, e.g. Team Falcon','اسم الغرفة، مثل: فريق الصقر')} onChange={e=>setName(e.target.value)}/><input value={focus} maxLength={100} placeholder={t('Project focus (optional)','محور المشروع (اختياري)')} onChange={e=>setFocus(e.target.value)}/><button className="btn primary" disabled={busy||!name.trim()}><Plus size={16}/>{t('Add room','إضافة غرفة')}</button></form>
   <p className="inline-help">{t('Without a focus, a room starts from the main challenge. Each room can change its own challenge in its settings.','دون محور، تبدأ الغرفة من التحدي الرئيسي. ويمكن لكل غرفة تعديل تحديها من إعداداتها.')}</p>
   <div className="toggle-list"><label className="toggle-row"><input type="checkbox" role="switch" checked={c.studentRooms!==false} disabled={busy} onChange={e=>void control({studentRooms:e.target.checked})}/><span className="toggle-text"><strong>{t('Students can create their own rooms','يمكن للطلاب إنشاء غرفهم')}</strong><small>{t('A team with its own idea opens a room and invites anyone.','الفريق صاحب الفكرة يفتح غرفة ويدعو من يشاء.')}</small></span></label><label className="toggle-row"><input type="checkbox" role="switch" checked={c.gallery!==false} disabled={busy} onChange={e=>void control({gallery:e.target.checked})}/><span className="toggle-text"><strong>{t('Students can visit other rooms','يمكن للطلاب زيارة الغرف الأخرى')}</strong><small>{t('Visitors read and comment but cannot post ideas or vote there.','الزوار يقرؤون ويعلّقون لكن لا يضيفون أفكاراً ولا يصوّتون.')}</small></span></label></div>
  </section>
  {rooms.length>0&&<section className="rooms-section"><h3>{t('Guide all rooms','توجيه كل الغرف')}</h3>
   <div className="actions"><label className="inline-field">{t('Move every room to','انقل كل الغرف إلى')}<select value={stage} onChange={e=>setStage(Number(e.target.value))}>{stages.map((s,i)=><option key={s} value={i}>{i+1}. {t(s,stageArabic[i])}</option>)}</select></label><button className="btn secondary" disabled={busy} onClick={()=>void run({action:'roomsControl',patch:{stage}},t('All rooms moved','تم نقل كل الغرف'))}><ArrowRight size={16}/>{t('Move','نقل')}</button><button className="btn secondary" disabled={busy} onClick={()=>void run({action:'roomsControl',patch:{paused:true}},t('All rooms paused','تم إيقاف كل الغرف'))}><Pause size={16}/>{t('Pause all','إيقاف الكل')}</button><button className="btn secondary" disabled={busy} onClick={()=>void run({action:'roomsControl',patch:{paused:false,submissionsOpen:true}},t('All rooms resumed','تم استئناف كل الغرف'))}><Play size={16}/>{t('Resume all','استئناف الكل')}</button><button className="btn secondary" onClick={()=>{void control({screen:'rooms'});present()}}><Monitor size={16}/>{t('Show rooms on projector','عرض الغرف على الشاشة')}</button></div>
   <form className="room-create" onSubmit={e=>{e.preventDefault();void control({broadcast:message}).then(ok=>{if(ok)setDraft(null);return ok}).then(ok=>ok&&notify(message?t('Message sent to every room','تم إرسال الرسالة إلى كل الغرف'):t('Message cleared','تم مسح الرسالة')))}}><input value={message} maxLength={300} placeholder={t('Message to every room, e.g. 5 minutes left — choose your best idea','رسالة لكل الغرف، مثل: بقيت 5 دقائق — اختاروا أفضل فكرة')} onChange={e=>setMessage(e.target.value)}/><button className="btn primary" disabled={busy||message===(c.broadcast||'')}><Megaphone size={16}/>{t('Send','إرسال')}</button>{c.broadcast&&<button type="button" className="btn ghost" disabled={busy} onClick={()=>void control({broadcast:''}).then(()=>setDraft(null))}>{t('Clear','مسح')}</button>}</form>
  </section>}
  {rooms.length>0&&<section className="rooms-section"><h3>{t('Team showcase','عرض مشاريع الفرق')}</h3><p className="inline-help">{t('Each team presents its project brief on the projector. Then the whole class votes for the best project — never for their own team.','يعرض كل فريق ملخص مشروعه على الشاشة، ثم يصوّت الصف كله لأفضل مشروع — وليس لفريقه.')}</p>
   <div className="actions"><label className="inline-field">{t('Team on screen','الفريق على الشاشة')}<select value={c.showcaseRoom&&rooms.some(r=>r.code===c.showcaseRoom)?c.showcaseRoom:rooms[0].code} disabled={busy} onChange={e=>void control({showcaseRoom:e.target.value,screen:'showcase'})}>{rooms.map(r=><option key={r.code} value={r.code}>{r.name}</option>)}</select></label><button className="btn primary" disabled={busy} onClick={()=>{void control({screen:'showcase',showcaseRoom:c.showcaseRoom||rooms[0].code});present()}}><Monitor size={16}/>{t('Present showcase','اعرض المشاريع')}</button><button className={'btn '+(c.showcaseVoting?'danger':'secondary')} disabled={busy} onClick={()=>void control({showcaseVoting:!c.showcaseVoting})}><Vote size={16}/>{c.showcaseVoting?t('Close class voting','إغلاق تصويت الصف'):t('Open class voting','فتح تصويت الصف')}</button><button className="btn secondary" disabled={busy} onClick={()=>{void control({screen:'showcaseResults'});present()}}><Trophy size={16}/>{t('Show results','عرض النتائج')}</button><span className="muted">{rooms.reduce((n,r)=>n+(r.votes||0),0)} {t('class votes','صوت')}</span></div>
  </section>}
  {rooms.length>0&&<RoomManager rooms={rooms} lang={lang} busy={busy} run={run} reload={reload} notify={notify}/>}
 </div>}

const screens:[string,string,string][]=[['stage','Current step','الخطوة الحالية'],['wall','Idea wall','جدار الأفكار'],['voting','Voting results','نتائج التصويت'],['qr','Join QR code','رمز الانضمام']];
type RoomSort='created'|'name'|'members'|'ideas'|'stage'|'pending'|'active';
const roomSorts:[RoomSort,string,string][]=[['created','Order created','ترتيب الإنشاء'],['name','Name A–Z','الاسم أبجدياً'],['members','Most members','الأكثر أعضاء'],['ideas','Most ideas','الأكثر أفكاراً'],['stage','Furthest along','الأكثر تقدماً'],['pending','Needs approval','بانتظار الموافقة'],['active','Recently active','الأحدث نشاطاً']];
const sortRooms:Record<RoomSort,(a:RoomSummary,b:RoomSummary)=>number>={created:(a,b)=>a.created-b.created,name:(a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base',numeric:true}),members:(a,b)=>b.members-a.members,ideas:(a,b)=>b.ideas-a.ideas,stage:(a,b)=>b.stage-a.stage,pending:(a,b)=>b.pending-a.pending,active:(a,b)=>(b.lastActivity||0)-(a.lastActivity||0)};
const SORT_KEY='ai-collab-room-sort';
const readSort=():RoomSort=>{try{const v=localStorage.getItem(SORT_KEY);if(roomSorts.some(([k])=>k===v))return v as RoomSort}catch{/* private mode */}return 'created'};

/** Every room of a workshop: search, sort, edit, choose what each room's screen shows, open, invite or delete. */
function RoomManager({rooms,lang,busy,run,reload,notify}:{rooms:RoomSummary[];lang:Language;busy:boolean;run:(body:Record<string,unknown>,success?:string)=>Promise<boolean>;reload:()=>Promise<void>;notify:(m:string)=>void}){
 const t=translator(lang);
 const [query,setQuery]=useState(''),[sort,setSort]=useState<RoomSort>(readSort),[allScreen,setAllScreen]=useState('stage'),[deleting,setDeleting]=useState(''),[editing,setEditing]=useState<RoomSummary|null>(null),[form,setForm]=useState({name:'',challenge:'',question:''}),[working,setWorking]=useState(false),[error,setError]=useState(''),[view,setView]=useState<RoomView>(()=>readView('map')),[openCode,setOpenCode]=useState('');
 const disabled=busy||working;const opened=rooms.find(r=>r.code===openCode);
 const chooseView=(v:RoomView)=>{setView(v);saveView(v)};
 const list=rooms.filter(r=>!query||(r.name+' '+r.challenge+' '+r.code).toLowerCase().includes(query.toLowerCase())).sort(sortRooms[sort]);
 function chooseSort(v:RoomSort){setSort(v);try{localStorage.setItem(SORT_KEY,v)}catch{/* private mode */}}
 async function roomControl(code:string,patch:Record<string,unknown>,success:string){setWorking(true);setError('');try{await action({action:'control',code,patch});await reload();notify(success);return true}catch(e){setError((e as Error).message);return false}finally{setWorking(false)}}
 const copy=async(code:string)=>{if(await copyText(joinLink(code)))notify(t('Invite link copied','تم نسخ رابط الدعوة'))};
 function edit(r:RoomSummary){setEditing(r);setForm({name:r.name,challenge:r.challenge,question:r.question})}
 /** Everything the presenter can do with one room. */
 const actionsFor=(r:RoomSummary)=>deleting===r.code?<><span className="muted">{t('Delete this room and everything in it?','حذف هذه الغرفة وكل ما فيها؟')}</span><button className="btn small danger" disabled={disabled} onClick={()=>void run({action:'deleteRoom',room:r.code,confirm:r.code},t('Room deleted','تم حذف الغرفة')).then(()=>setDeleting(''))}>{t('Delete','حذف')}</button><button className="btn small secondary" onClick={()=>setDeleting('')}>{t('Keep','إبقاء')}</button></>
   :<><label className="room-screen"><Monitor size={14}/><span className="sr-only">{t('This room’s screen shows','شاشة هذه الغرفة تعرض')}</span><select value={screens.some(([k])=>k===r.screen)?r.screen:'stage'} disabled={disabled} title={t('What this room’s screen shows','ما تعرضه شاشة هذه الغرفة')} onChange={e=>void roomControl(r.code,{screen:e.target.value},t('Room screen updated','تم تحديث شاشة الغرفة'))}>{screens.map(([k,en,ar])=><option key={k} value={k}>{t(en,ar)}</option>)}</select></label>
    <a className="btn small primary" href={appUrl('/presenter?code=')+r.code} target="_blank" rel="noreferrer"><ExternalLink size={14}/>{t('Open & guide','فتح وتوجيه')}</a><a className="btn small secondary" href={appUrl('/project?code=')+r.code} target="_blank" rel="noreferrer"><Monitor size={14}/>{t('Project','عرض')}</a><button className="btn small secondary" onClick={()=>void copy(r.code)}><Copy size={14}/>{t('Invite link','رابط الدعوة')}</button><button className="btn small ghost icon-btn" aria-label={t('Edit room','تعديل الغرفة')} title={t('Edit room','تعديل الغرفة')} onClick={()=>edit(r)}><Pencil size={14}/></button><button className="btn small ghost icon-btn" aria-label={t('Delete room','حذف الغرفة')} title={t('Delete room','حذف الغرفة')} onClick={()=>setDeleting(r.code)}><Trash2 size={14}/></button></>;
 return <section className="room-manager">
  <div className="room-toolbar"><ViewSwitch view={view} onChange={chooseView} lang={lang}/><label className="room-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search rooms…','ابحث في الغرف…')} aria-label={t('Search rooms','ابحث في الغرف')}/></label><label className="inline-field">{t('Sort','ترتيب')}<select value={sort} onChange={e=>chooseSort(e.target.value as RoomSort)}>{roomSorts.map(([k,en,ar])=><option key={k} value={k}>{t(en,ar)}</option>)}</select></label><label className="inline-field">{t('All room screens show','كل شاشات الغرف تعرض')}<select value={allScreen} onChange={e=>setAllScreen(e.target.value)}>{screens.map(([k,en,ar])=><option key={k} value={k}>{t(en,ar)}</option>)}</select></label><button className="btn small secondary" disabled={disabled} onClick={()=>void run({action:'roomsControl',patch:{screen:allScreen}},t('Every room screen updated','تم تحديث شاشات كل الغرف'))}><Monitor size={14}/>{t('Apply','تطبيق')}</button></div>
  {error&&<div role="alert" className="error">{error}</div>}
  {view==='map'?<RoomsMap rooms={list} lang={lang} title={t('Main workshop','الورشة الرئيسية')} onOpen={r=>setOpenCode(r.code)}/>
  :view==='list'?<RoomsList rooms={list} lang={lang} onOpen={r=>setOpenCode(r.code)}/>
  :<div className="room-grid">{list.map(r=><RoomTile key={r.code} room={r} lang={lang}><button className="btn small secondary" onClick={()=>setOpenCode(r.code)}><Eye size={14}/>{t('Details & activity','التفاصيل والنشاط')}</button>{actionsFor(r)}</RoomTile>)}</div>}
  {opened&&<Modal wide title={opened.name+' · '+roomNumber(opened.code)} onClose={()=>setOpenCode('')}><div className="room-detail"><p className="room-focus">{opened.challenge}</p><div className="room-detail-step"><StageTrack stage={opened.stage} lang={lang}/><span>{t('Step','الخطوة')} {opened.stage+1}/9 · {t(stages[opened.stage],stageArabic[opened.stage])}</span>{isLive(opened)&&<span className="pill lime"><span className="live-dot"/>{t('Active now','نشطة الآن')}</span>}{opened.paused&&<span className="pill">{t('Paused','متوقفة')}</span>}{opened.ended&&<span className="pill">{t('Ended','انتهت')}</span>}</div><RoomStats room={opened} lang={lang} large/><div className="room-actions">{actionsFor(opened)}</div><RoomActivity code={opened.code} lang={lang}/></div></Modal>}
  {!list.length&&<p className="muted">{t('No rooms match your search.','لا توجد غرف تطابق البحث.')}</p>}
  {editing&&<Modal title={t('Edit room','تعديل الغرفة')+' · '+roomNumber(editing.code)} onClose={()=>setEditing(null)}><form className="stack" onSubmit={e=>{e.preventDefault();void roomControl(editing.code,form,t('Room saved','تم حفظ الغرفة')).then(ok=>ok&&setEditing(null))}}><label>{t('Room name','اسم الغرفة')}<input value={form.name} maxLength={60} required onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t('Project focus','محور المشروع')}<input value={form.challenge} maxLength={100} required onChange={e=>setForm({...form,challenge:e.target.value})}/></label><label>{t('Challenge question','سؤال التحدي')}<textarea value={form.question} maxLength={1000} required onChange={e=>setForm({...form,question:e.target.value})}/></label><button className="btn primary" disabled={disabled}>{t('Save room','حفظ الغرفة')}</button></form></Modal>}
 </section>}

/** The rooms manager for one workshop, opened from the presenter dashboard. Stays live while open. */
export function WorkshopRooms({code,lang}:{code:string;lang:Language}){const t=translator(lang);const {data,refresh,error}=useWorkshop(code);const {toast,notify}=useToast();const [busy,setBusy]=useState(false),[failure,setFailure]=useState('');
 async function run(body:Record<string,unknown>,success?:string){setBusy(true);setFailure('');try{await action({...body,code});await refresh();if(success)notify(success);return true}catch(e){setFailure((e as Error).message);return false}finally{setBusy(false)}}
 if(!data)return <p className="connecting">{error||<><span className="spinner"/>{t('Loading rooms…','جارٍ تحميل الغرف…')}</>}</p>;
 return <>{failure&&<div role="alert" className="error">{failure}</div>}<RoomsPanel data={data} lang={lang} busy={busy} run={run} control={patch=>run({action:'control',patch})} reload={refresh} notify={notify} present={()=>window.open(appUrl('/project?code=')+code,'_blank','noopener')}/>{toast&&<div className="toast" role="status">{toast}</div>}</>}

const MEDALS=['🥇','🥈','🥉'];
/** Projector: one team's project at a time, or the class vote results. */
export function ShowcaseScreen({data,lang,admin,control}:{data:Snapshot;lang:Language;admin:boolean;control:(patch:Partial<Config>)=>Promise<boolean>}){const t=translator(lang);const c=data.config;const rooms=data.rooms||[];
 if(!rooms.length)return <div className="center"><h1>{t('Team showcase','عرض مشاريع الفرق')}</h1><p className="subtitle">{t('No team rooms yet.','لا توجد غرف فرق بعد.')}</p></div>;
 if(c.screen==='showcaseResults'){const ranked=[...rooms].sort((a,b)=>(b.votes||0)-(a.votes||0));const max=Math.max(1,...ranked.map(r=>r.votes||0));const total=ranked.reduce((n,r)=>n+(r.votes||0),0);
  return <div className="center"><span className="eyebrow">{t('TEAM SHOWCASE','عرض مشاريع الفرق')}</span><h1>{t('The class has chosen','اختار الصف')}</h1><p className="subtitle">{total} {t('votes from the class','صوتاً من الصف')}</p><div className="results showcase-results">{ranked.map((r,i)=><div className={'result'+(i===0&&(r.votes||0)>0?' leader':'')} key={r.code}><div className="result-title"><strong><span className="result-rank">{(r.votes||0)>0&&MEDALS[i]?MEDALS[i]:String(i+1).padStart(2,'0')}</span>{r.name}</strong><span className="result-count">{r.votes??'–'}<small>{total?Math.round((r.votes||0)/total*100):0}%</small></span></div><div className="bar-track"><div className="bar-fill" style={{width:(r.votes||0)/max*100+'%',background:i===0?'var(--accent-fill)':i===1?'var(--purple)':'var(--teal)'}}/></div><small>{r.brief.solution||r.challenge}</small></div>)}</div>{c.showcaseVoting&&<p className="pill lime">{t('Voting is still open','التصويت ما زال مفتوحاً')}</p>}</div>}
 const i=Math.max(0,rooms.findIndex(r=>r.code===c.showcaseRoom));const r=rooms[i];const go=(n:number)=>void control({showcaseRoom:rooms[(n+rooms.length)%rooms.length].code,screen:'showcase'});
 const parts=([['Problem','المشكلة',r.brief.problem],['Users','المستخدمون',r.brief.users],['Core features','الميزات الأساسية',r.brief.features]] as const).filter(p=>p[2]);
 return <div className="center showcase"><span className="eyebrow">{t(`TEAM SHOWCASE · ${i+1} OF ${rooms.length}`,`عرض مشاريع الفرق · ${i+1} من ${rooms.length}`)}</span><h1><DoorOpen size={44}/> {r.name}</h1><p className="subtitle">{r.brief.solution||r.challenge}</p>
  {parts.length?<div className="canvas-grid showcase-brief">{parts.map(([en,ar,text])=><div className="panel" key={en}><h3>{t(en,ar)}</h3><p>{text}</p></div>)}</div>:<p className="muted">{t('This team’s project brief is not ready yet — invite them to present their best ideas.','ملخص مشروع هذا الفريق غير جاهز بعد — ادعهم لعرض أفضل أفكارهم.')}</p>}
  <div className="showcase-stats"><span><Users size={18}/>{r.members} {t('members','أعضاء')}</span><span><Lightbulb size={18}/>{r.ideas} {t('ideas','أفكار')}</span></div>
  <h2 className="showcase-ask">{t('What works? What would you improve?','ما الذي ينجح؟ وما الذي ستحسّنه؟')}</h2>
  {c.showcaseVoting&&<p className="pill lime">{t('Class voting is open — vote on your phone','تصويت الصف مفتوح — صوّت من هاتفك')}</p>}
  {admin&&rooms.length>1&&<div className="actions showcase-nav"><button className="btn secondary" onClick={()=>go(i-1)}><ChevronLeft size={18}/>{t('Previous team','الفريق السابق')}</button><button className="btn primary" onClick={()=>go(i+1)}>{t('Next team','الفريق التالي')}<ChevronRight size={18}/></button></div>}
 </div>}

/** Students on the main workshop: see every team's project and vote for the best one (not their own). */
export function ShowcaseVote({data,lang,refresh}:{data:Snapshot;lang:Language;refresh:()=>Promise<void>}){const t=translator(lang);const c=data.config;const rooms=data.rooms||[];const mine=data.me?.room||null;const vote=data.me?.showcaseVote||null;
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!rooms.length||!(c.showcaseVoting||c.screen==='showcase'||c.screen==='showcaseResults'))return null;
 async function choose(room:string){setBusy(true);setError('');try{await action({action:'showcaseVote',code:data.code,room});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel showcase-vote"><span className="eyebrow"><Trophy size={14}/> {t('TEAM SHOWCASE','عرض مشاريع الفرق')}</span><h2>{c.showcaseVoting?t('Vote for the best team project','صوّت لأفضل مشروع فريق'):t('Team projects','مشاريع الفرق')}</h2><p className="inline-help">{c.showcaseVoting?t('One vote. You can change it until voting closes. Choose another team’s project, not your own.','صوت واحد، ويمكنك تغييره حتى يُغلق التصويت. اختر مشروع فريق آخر، لا فريقك.'):t('Voting opens when the presenter starts it.','يبدأ التصويت عندما يفتحه مقدم الورشة.')}</p>
  <div className="room-grid">{rooms.map(r=>{const own=r.code===mine,chosen=r.code===vote;return <RoomTile key={r.code} room={r} lang={lang} mine={own}>{r.brief.solution&&<p className="showcase-solution">{r.brief.solution}</p>}{r.votes!==null&&<span className="pill">{r.votes} {r.votes===1?t('vote','صوت'):t('votes','صوت')}</span>}{own?<span className="muted">{t('Your team — vote for another','فريقك — صوّت لفريق آخر')}</span>:c.showcaseVoting&&<button className={'btn small '+(chosen?'secondary':'primary')} disabled={busy||chosen} onClick={()=>void choose(r.code)}>{chosen?<><Check size={14}/>{t('Your vote','صوتك')}</>:<><Vote size={14}/>{t('Vote for this project','صوّت لهذا المشروع')}</>}</button>}</RoomTile>})}</div>
  {error&&<div role="alert" className="error">{error}</div>}
 </section>}

/** Student tab on the main workshop: find your team, visit others, or start a room. */
export function StudentRooms({data,lang}:{data:Snapshot;lang:Language}){const t=translator(lang);const c=data.config;const rooms=data.rooms||[];const mine=data.me?.room||null;const current=rooms.find(r=>r.code===mine);
 const [name,setName]=useState(''),[focus,setFocus]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState('');
 async function enter(body:Record<string,unknown>){setBusy(true);setError('');try{const r=await action(body) as {code?:string};goTo(r.code||String(body.code))}catch(e){setError((e as Error).message);setBusy(false)}}
 const [view,setView]=useState<RoomView>(()=>{const v=readView('map');return v==='list'?'map':v}),[peek,setPeek]=useState('');const peeked=rooms.find(r=>r.code===peek);
 const chooseView=(v:RoomView)=>{setView(v);saveView(v)};
 const buttons=(r:RoomSummary)=>{const isMine=r.code===mine;return <>{isMine?<button className="btn small primary" onClick={()=>goTo(r.code)}>{t('Open','افتح')}</button>
   :confirm===r.code?<><span className="muted">{t(`Move from ${current?.name} to this team?`,`الانتقال من ${current?.name} إلى هذا الفريق؟`)}</span><button className="btn small primary" disabled={busy} onClick={()=>void enter({action:'joinRoom',code:r.code})}>{t('Move','انتقال')}</button><button className="btn small secondary" onClick={()=>setConfirm('')}>{t('Cancel','إلغاء')}</button></>
   :<>{!r.ended&&<button className="btn small primary" disabled={busy} onClick={()=>current?setConfirm(r.code):void enter({action:'joinRoom',code:r.code})}><UserPlus size={14}/>{t('Join this team','انضم لهذا الفريق')}</button>}{c.gallery!==false&&<button className="btn small secondary" disabled={busy} onClick={()=>void enter({action:'joinRoom',code:r.code,role:'guest'})}><Eye size={14}/>{t('Visit','زيارة')}</button>}</>}</>};
 return <section className="student-rooms">
  {current?<div className="panel my-room"><span className="eyebrow">{t('YOUR TEAM ROOM','غرفة فريقك')}</span><h2>{current.name}</h2><p className="muted">{current.challenge}</p><button className="btn primary full-width" onClick={()=>goTo(current.code)}>{t('Open my room','افتح غرفتي')} <ArrowRight size={17}/></button></div>
  :<p className="inline-help">{t('Choose a team to develop your own project with. You can still visit other rooms to see their ideas and comment.','اختر فريقاً لتطوير مشروعكم الخاص. ويمكنك زيارة الغرف الأخرى لرؤية أفكارها والتعليق عليها.')}</p>}
  {rooms.length?<><div className="student-rooms-bar"><ViewSwitch view={view} onChange={chooseView} lang={lang} list={false}/></div>{view==='map'?<RoomsMap rooms={rooms} lang={lang} title={c.name} mine={mine} onOpen={r=>setPeek(r.code)}/>:<div className="room-grid">{rooms.map(r=><RoomTile key={r.code} room={r} lang={lang} mine={r.code===mine}>{buttons(r)}</RoomTile>)}</div>}{peeked&&<Modal title={peeked.name} onClose={()=>setPeek('')}><RoomTile room={peeked} lang={lang} mine={peeked.code===mine}>{buttons(peeked)}</RoomTile></Modal>}</>:<div className="empty"><span className="empty-icon"><DoorOpen size={26}/></span><h3>{t('No team rooms yet','لا توجد غرف فرق بعد')}</h3>{c.studentRooms!==false?t('Start one below and invite your teammates.','أنشئ غرفة أدناه وادعُ زملاءك.'):t('Your presenter will open the rooms.','سيفتح مقدم الورشة الغرف.')}</div>}
  {c.studentRooms!==false&&!c.ended&&<form className="panel stack" onSubmit={e=>{e.preventDefault();void enter({action:'createRoom',code:data.code,name,challenge:focus})}}><h3>{t('Start a room for your team','أنشئ غرفة لفريقك')}</h3><label>{t('Room name','اسم الغرفة')}<input value={name} maxLength={60} required onChange={e=>setName(e.target.value)} placeholder={t('e.g. Team Falcon','مثل: فريق الصقر')}/></label><label>{t('Your project idea (optional)','فكرة مشروعكم (اختياري)')}<input value={focus} maxLength={100} onChange={e=>setFocus(e.target.value)} placeholder={t('e.g. Smart parking for campus','مثل: مواقف ذكية للحرم الجامعي')}/></label><small className="muted">{t('You will lead the room: you move it through the steps and can invite anyone with its link.','ستقود الغرفة: تنقلها بين الخطوات ويمكنك دعوة أي شخص برابطها.')}</small><button className="btn primary full-width" disabled={busy||!name.trim()}><Plus size={17}/>{t('Create room','إنشاء الغرفة')}</button></form>}
  {error&&<div role="alert" className="error">{error}</div>}
 </section>}

/** Shown inside a team room: where you are, your role, inviting others and moving between rooms. */
export function RoomBanner({data,lang,onLead,refresh}:{data:Snapshot;lang:Language;onLead:()=>void;refresh:()=>Promise<void>}){const t=translator(lang);const parent=data.parent!;const role=data.me?.role||'member';const others=(data.rooms||[]).filter(r=>r.code!==data.code);
 const [modal,setModal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 async function join(){setBusy(true);setError('');try{await action({action:'joinRoom',code:data.code});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function visit(code:string){setBusy(true);setError('');try{await action({action:'joinRoom',code,role:'guest'});goTo(code)}catch(e){setError((e as Error).message);setBusy(false)}}
 const link=joinLink(data.code);
 return <section className={'room-banner'+(role==='guest'?' guest':'')}>
  <div className="room-banner-top"><div><span className="eyebrow">{t('TEAM ROOM','غرفة الفريق')} · <span dir="ltr">{roomNumber(data.code)}</span></span><h2><DoorOpen size={20}/>{data.config.name}</h2><span className="muted">{t('Part of','ضمن')} {parent.name}</span></div>
   <span className={'pill '+(role==='guest'?'':'lime')}>{role==='lead'?<><Crown size={13}/> {t('Room lead','قائد الغرفة')}</>:role==='guest'?<><Eye size={13}/> {t('Visitor','زائر')}</>:<><Users size={13}/> {t('Member','عضو')}</>}</span></div>
  <div className="actions">{role==='lead'&&<button className="btn small primary" onClick={onLead}><Crown size={15}/>{t('Lead the room','قيادة الغرفة')}</button>}{role!=='guest'&&<button className="btn small secondary" onClick={()=>setModal('invite')}><Share2 size={15}/>{t('Invite','دعوة')}</button>}{parent.gallery&&others.length>0&&<button className="btn small secondary" onClick={()=>setModal('rooms')}><DoorOpen size={15}/>{t('Other rooms','الغرف الأخرى')}</button>}<a className="btn small ghost" href={appUrl('/join?code=')+parent.code}><ArrowLeft size={15}/>{t('Main workshop','الورشة الرئيسية')}</a></div>
  {role==='guest'&&<div className="room-guest"><p>{t('You are visiting: read the ideas and leave comments to help this team. Members add ideas and vote.','أنت في زيارة: اقرأ الأفكار واترك تعليقات لمساعدة هذا الفريق. الأعضاء يضيفون الأفكار ويصوّتون.')}</p>{!data.config.ended&&<button className="btn small primary" disabled={busy} onClick={()=>void join()}><UserPlus size={15}/>{t('Join this team instead','انضم لهذا الفريق بدلاً من ذلك')}</button>}</div>}
  {role==='lead'&&<p className="inline-help">{t('As the room lead you move your team through the steps, choose the idea to develop, run the vote and prepare your project brief.','بصفتك قائد الغرفة تنقل فريقك بين الخطوات، وتختار الفكرة للتطوير، وتدير التصويت، وتجهز ملخص مشروعكم.')}</p>}
  {error&&<div role="alert" className="error">{error}</div>}
  {modal==='invite'&&<Modal title={t('Invite people to this room','ادعُ آخرين إلى هذه الغرفة')} onClose={()=>setModal('')}><div className="qr"><QRCodeSVG value={link} size={240} level="M" bgColor="#fff" fgColor="#101216" marginSize={0} title={t('Scan to join this room','امسح للانضمام إلى هذه الغرفة')}/><div className="session-code" dir="ltr">{data.code}</div><p className="join-link" dir="ltr">{link}</p></div><p className="inline-help">{t('Anyone with this link or code can join your room, even if they are new to the workshop.','يمكن لأي شخص لديه هذا الرابط أو الرمز الانضمام إلى غرفتك، حتى لو كان جديداً على الورشة.')}</p><button className="btn primary full-width" onClick={()=>void copyText(link).then(ok=>setCopied(ok))}><Copy size={16}/>{copied?t('Link copied ✓','تم نسخ الرابط ✓'):t('Copy invite link','نسخ رابط الدعوة')}</button></Modal>}
  {modal==='rooms'&&<Modal wide title={t('Visit another room','زيارة غرفة أخرى')} onClose={()=>setModal('')}><p className="inline-help">{t('See what other teams are building and leave helpful comments. Visiting does not change your own team.','شاهد ما تبنيه الفرق الأخرى واترك تعليقات مفيدة. الزيارة لا تغيّر فريقك.')}</p><div className="room-grid">{others.map(r=><RoomTile key={r.code} room={r} lang={lang}><button className="btn small primary" disabled={busy} onClick={()=>void visit(r.code)}><Eye size={14}/>{t('Visit','زيارة')}</button></RoomTile>)}</div></Modal>}
 </section>}

/** On the main workshop's task screen: a shortcut back to your team. */
export function MyRoomLink({data,lang}:{data:Snapshot;lang:Language}){const t=translator(lang);const room=(data.rooms||[]).find(r=>r.code===data.me?.room);if(!room)return null;return <button className="my-room-link" onClick={()=>goTo(room.code)}><DoorOpen size={18}/><span><small>{t('Your team room','غرفة فريقك')}</small><strong>{room.name}</strong></span><ArrowRight size={17}/></button>}
