export type Language = 'en'|'ar'|'both';
export const stages = ['Welcome','Problem','Ideas','Solutions','Improve','Vote','Human + AI','Product','Reflection'];
export const stageArabic = ['الترحيب','المشكلة','الأفكار','الحلول','التحسين','التصويت','الإنسان والذكاء الاصطناعي','المنتج','التأمل'];
export const skills = ['Problem Solving','Creativity','Collaboration','Communication','Critical Thinking','Decision Making','AI Literacy','Product Development'];
export const skillArabic = ['حل المشكلات','الإبداع','التعاون','التواصل','التفكير النقدي','اتخاذ القرار','الوعي بالذكاء الاصطناعي','تطوير المنتجات'];
export const skillIcons = ['🧠','💡','🤝','🗣','🔎','⚖️','🤖','🛠'];
export type Config={name:string;challenge:string;question:string;description:string;language:Language;anonymous:boolean;moderated:boolean;liveResults:boolean;multiple:boolean;maxVotes:number;stage:number;paused:boolean;submissionsOpen:boolean;votingOpen:boolean;ended:boolean;spotlight:string|null;screen:string;timerEnd:number|null;selected:string[];canvas:Record<string,string>;prompt:string;revision:string;reveal:number;/** Main workshop only: team rooms are on, students may create rooms, students may visit other rooms as guests, and a message shown in every room. Missing in older workshops. */teamRooms?:boolean;studentRooms?:boolean;gallery?:boolean;broadcast?:string;/** Showcase: the team on the projector, and whether the class is voting for the best team project. */showcaseRoom?:string|null;showcaseVoting?:boolean;};
/** One team room as listed on the main workshop and in every room (for visiting). */
export type RoomSummary={code:string;name:string;challenge:string;question:string;stage:number;screen:string;paused:boolean;ended:boolean;members:number;ideas:number;pending:number;created:number;/** The room's project brief (from its product canvas) for the showcase. */brief:{problem:string;users:string;solution:string;features:string};/** Class showcase votes; null while hidden. */votes:number|null;/** Visitors (guests), approved comments (the room's messages), votes on ideas inside the room, and when anything was last posted. */guests:number;comments:number;ideaVotes:number;lastActivity:number|null;/** Up to 16 members, lead first. */people:{name:string;lead:boolean}[]};
export type Idea={id:string;code:string;participant:string;nickname:string;type:string;parent:string|null;title:string;text:string;status:string;shortlisted:number;highlighted:number;sortOrder:number;created:number;votes:number|null;/** Set when title/text are shown translated; holds what the author wrote. */orig?:{title:string;text:string};};
export type Snapshot={code:string;config:Config;ideas:Idea[];stats:{participants:number;ideas:number;improvements:number;votes:number};reflection:Record<string,number>;isPresenter:boolean;/** Set when workshop text is shown translated; holds the presenter's original wording. */original?:{name:string;challenge:string;question:string;description:string};me:{id:string;nickname:string;votes:string[];reflection:string|null;submitted:string[];/** In a team room: member, lead or guest. */role?:string;/** In the main workshop: the room this student belongs to. */room?:string|null;/** In the main workshop: the team project this student voted for in the showcase. */showcaseVote?:string|null}|null;/** Team rooms of the main workshop (on the main workshop and on every room). */rooms?:RoomSummary[];/** Set on a team room: the main workshop it belongs to. */parent?:{code:string;name:string;challenge:string;broadcast:string;gallery:boolean;studentRooms:boolean;ended:boolean};/** On a team room the visitor has not joined yet: their nickname in the main workshop. */viewer?:{nickname:string}|null;/** Presenter and room lead only: everyone in this workshop or room. */people?:{nickname:string;role:string;created:number}[];};
export const defaults:Config={name:'AI COLLAB LAB',challenge:'Your Healthcare Assistant',question:'How can we use technology and AI to create a useful healthcare assistant for university students?',description:'Think • Share • Improve • Vote • Build',language:'en',anonymous:true,moderated:false,liveResults:true,multiple:true,maxVotes:3,stage:0,paused:false,submissionsOpen:true,votingOpen:false,ended:false,spotlight:null,screen:'stage',timerEnd:null,selected:[],canvas:{},prompt:'',revision:'',reveal:0,teamRooms:false,studentRooms:true,gallery:true,broadcast:''};
export const canvasNames=['Problem','Users','Solution','Features','Value','AI Role','Human Role','Risks','Responsible AI'];
export const canvasArabic=['المشكلة','المستخدمون','الحل','الميزات','القيمة','دور الذكاء الاصطناعي','دور الإنسان','المخاطر','الذكاء الاصطناعي المسؤول'];
export const prompts=['Welcome to the innovation team','What problem should we solve?','What could make a difference?','Become a solution designer','Make this idea better','Time to decide','AI amplifies good thinking','Let’s build our product','What did you practice today?'];
export const promptsAr=['مرحباً بك في فريق الابتكار','ما المشكلة التي ينبغي أن نحلها؟','ما الفكرة التي يمكن أن تحدث فرقاً؟','كن مصمماً للحلول','اجعل هذه الفكرة أفضل','حان وقت القرار','الذكاء الاصطناعي يعزز التفكير الجيد','لنبنِ منتجنا معاً','ما المهارات التي مارستها اليوم؟'];
export function generateCanvas(s:Snapshot):Record<string,string>{const ar=s.config.language==='ar',L=(en:string,arabic:string)=>ar?arabic:en;const selected=s.ideas.filter(i=>s.config.selected.includes(i.id));const problems=s.ideas.filter(i=>i.type==='problem'&&i.status==='approved');const improvements=s.ideas.filter(i=>i.type==='improvement'&&selected.some(p=>p.id===i.parent));return {'Problem':problems.map(i=>i.text).join('\n')||s.config.question,'Users':L('Describe the people who will use this project and what they need.','صف الأشخاص الذين سيستخدمون هذا المشروع وما يحتاجون إليه.'),'Solution':selected.map(i=>i.title).join(' + ')||s.config.challenge,'Features':selected.map(i=>i.title+': '+i.text).concat(improvements.map(i=>i.text)).join('\n')||L('Select ideas from the finalists to define the core features.','اختر أفكاراً من المرشحين لتحديد الميزات الأساسية.'),'Value':L('A practical, accessible solution shaped by student experience and collective judgment.','حل عملي وسهل الوصول، تشكّله تجربة الطلاب وحكمهم الجماعي.'),'AI Role':L('Organize information, explain clearly, and suggest options. Keep uncertainty visible.','تنظيم المعلومات، والشرح بوضوح، واقتراح الخيارات، مع إظهار درجة عدم اليقين.'),'Human Role':L('Evaluate suggestions, verify accuracy, make decisions, and supervise sensitive uses.','تقييم الاقتراحات، والتحقق من الدقة، واتخاذ القرارات، والإشراف على الاستخدامات الحساسة.'),'Risks':L('Inaccurate AI output, privacy loss, accessibility barriers, and overreliance.','مخرجات غير دقيقة من الذكاء الاصطناعي، وفقدان الخصوصية، وعوائق الوصول، والاعتماد المفرط.'),'Responsible AI':L('Minimize personal data, request informed consent, explain limitations, support Arabic and English, and require human review for consequential decisions.','تقليل البيانات الشخصية، وطلب موافقة مستنيرة، وتوضيح حدود النظام، ودعم العربية والإنجليزية، واشتراط المراجعة البشرية للقرارات المهمة.')};}
export function generatePrompt(s:Snapshot,canvas:Record<string,string>):string{const visible=s.ideas.filter(i=>i.status==='approved');const section=(name:string,content:string)=>`# ${name}\n${content}\n`;return [section('PROJECT',`Build a mobile-friendly web application called ${s.config.challenge}.\nChallenge: ${s.config.question}`),section('TARGET USERS',canvas.Users||''),section('PROBLEM',canvas.Problem||''),section('SOLUTION',canvas.Solution||''),section('CORE FEATURES',canvas.Features||''),section('STUDENT CONTRIBUTIONS',visible.filter(i=>s.config.selected.includes(i.id)||(i.parent&&s.config.selected.includes(i.parent))).map(i=>`[${i.type}] ${i.title}: ${i.text}${i.parent?' (improves '+(visible.find(p=>p.id===i.parent)?.title||'selected idea')+')':''}`).join('\n')),section('VOTING RESULTS',visible.filter(i=>i.shortlisted).sort((a,b)=>(b.votes||0)-(a.votes||0)).map(i=>`${i.title}: ${i.votes||0} votes${s.config.selected.includes(i.id)?' — selected for product':''}`).join('\n')),section('VALUE',canvas.Value||''),section('USER EXPERIENCE','Simple mobile-first flows, thumb-friendly controls, visible save confirmation, clear loading and error states, keyboard access, and high-contrast accessible text. English and true Arabic RTL support.'),section('AI FEATURES',canvas['AI Role']||''),section('HUMAN OVERSIGHT',canvas['Human Role']||''),section('SAFETY',`${canvas.Risks||''}\n${canvas['Responsible AI']||''}\nIf this involves health, do not diagnose, prescribe, or interpret results as medical advice. Direct urgent concerns to qualified care. Never collect real patient data in a demonstration.`),section('SCREENS','Welcome, main workspace, core feature flows, saved history, settings, privacy and help.'),section('TECHNICAL REQUIREMENTS','Use React and TypeScript with a maintainable backend and durable database. Validate all inputs on the server, enforce authorization, protect secrets, and handle reconnects. The core experience must work without an AI API; provide a server-side adapter for optional future AI integration.'),section('EXPECTED RESULT','Deliver a working prototype with clear setup instructions and verification of the main user flows. Label simulated AI responses clearly. Preserve the selected student features and explain any unresolved product decisions.')].join('\n');}
