"use client";
import {useState,useEffect,useRef} from 'react';
import {Sparkles,Check,Users,Send,Pause,Lightbulb,ArrowRight,Vote,Wifi,WifiOff,DoorOpen,Eye,Crown,ArrowLeft,Lock} from 'lucide-react';
import {lessonSteps,lessonIndex} from '../../lib/lesson';
import StudentWall from '../../lib/student-wall';
import {Brand,T,LanguageSwitch,ThemeSwitch,TypeChip,useWorkshop,action,Results,Timer} from '../../lib/client';
import {Journey,Coach,QualityMeter,Celebrate,HumanAiQuiz,ReflectionInsight} from '../../lib/learning-ui';
import {prompts,promptsAr,skills,skillArabic,skillIcons,type Language} from '../../lib/workshop';
import {uid} from '../../lib/id';
import {setUiLang,storedLang} from '../../lib/i18n';
import {useTranslatedSnapshot,TranslationNotice} from '../../lib/translate-client';
import {NewHereBanner} from '../../lib/first-visit';
import {Broadcast,StudentRooms,RoomBanner,MyRoomLink,ShowcaseVote} from '../../lib/team-rooms';
import {RoomFiles} from '../../lib/rooms-visual';
import Console from '../../lib/console';

/** A student's own language choice (EN / العربية / both) wins over the workshop default and is remembered. */
const STUDENT_LANG='ai-collab-student-lang';
const readStudentLang=():Language|null=>{try{const v=localStorage.getItem(STUDENT_LANG);if(v==='en'||v==='ar'||v==='both')return v}catch{}return storedLang()};

const types:Record<number,string>={1:'problem',2:'idea',3:'solution',4:'improvement',7:'suggestion'};
const kinds=['Add something','Improve it','Find a weakness','Suggest an alternative'];
type Draft={text:string;title:string;kind:string};
const readDraft=(key:string):Draft=>{try{const d=JSON.parse(sessionStorage.getItem(key)||'null');if(d&&typeof d.text==='string')return {text:d.text,title:String(d.title||''),kind:kinds.includes(d.kind)?d.kind:kinds[0]}}catch{}return {text:'',title:'',kind:kinds[0]}};

export default function Join(){
 const [code,setCode]=useState(''),[entry,setEntry]=useState(''),[nickname,setNickname]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[lang,setLang]=useState<Language>(()=>(typeof window!=='undefined'&&readStudentLang())||(typeof document!=='undefined'&&document.documentElement.lang==='ar'?'ar':'en')),[text,setText]=useState(''),[title,setTitle]=useState(''),[kind,setKind]=useState(kinds[0]),[confirmation,setConfirmation]=useState(''),[welcome,setWelcome]=useState(false),[tab,setTab]=useState('auto'),[celebrate,setCelebrate]=useState(0),[leading,setLeading]=useState(false);
 const submissionId=useRef('');if(!submissionId.current)submissionId.current=uid();
 const textArea=useRef<HTMLTextAreaElement>(null);
 const {data:rawData,connected,refresh,error:loadError}=useWorkshop(code);
 const data=useTranslatedSnapshot(rawData,lang);
 const draftKey=data?`draft:${code}:${data.config.stage}:${data.config.spotlight||''}`:'';
 useEffect(()=>{const q=new URLSearchParams(location.search).get('code');if(q){setCode(q.toUpperCase());setEntry(q.toUpperCase())}},[]);
 useEffect(()=>{if(data)setLang(readStudentLang()||data.config.language)},[data?.config.language]);
 useEffect(()=>{setUiLang(lang==='ar'?'ar':'en')},[lang]);
 // A stage change starts a new task, but whatever the student had typed for this task is kept.
 const draftOwner=useRef('');
 useEffect(()=>{if(!draftKey)return;draftOwner.current=draftKey;setConfirmation('');setError('');const d=readDraft(draftKey);setText(d.text);setTitle(d.title);setKind(d.kind);submissionId.current=uid()},[draftKey]);
 useEffect(()=>{const key=draftOwner.current;if(!key)return;try{if(text||title)sessionStorage.setItem(key,JSON.stringify({text,title,kind}));else sessionStorage.removeItem(key)}catch{}},[text,title,kind]);
 async function run(body:Record<string,unknown>,after?:()=>void){setBusy(true);setError('');try{const result=await action({...body,code});await refresh();after?.();return result;}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const tr=(en:string,ar:string)=><T en={en} ar={ar} lang={lang}/>;
 function chooseLang(v:Language){setLang(v);try{localStorage.setItem(STUDENT_LANG,v)}catch{}if(v!=='both')setUiLang(v,true)}
 const ar=lang==='ar';

 if(!code||!data)return <main className="center-page join-entry"><div className="page-top"><Brand/><div className="actions"><LanguageSwitch lang={lang} onChange={chooseLang}/><ThemeSwitch/></div></div><NewHereBanner lang={lang}/><span className="eyebrow">{tr('THINK · SHARE · IMPROVE · VOTE · BUILD','فكّر · شارك · حسّن · صوّت · ابنِ')}</span><h1>{tr('Join the innovation team','انضم إلى فريق الابتكار')}</h1><p>{tr('Enter the workshop code shown on the presenter’s screen.','أدخل رمز الورشة المعروض على شاشة مقدم الورشة.')}</p><form className="panel stack" onSubmit={e=>{e.preventDefault();setCode(entry.trim().toUpperCase())}}><label>{tr('Workshop code','رمز الورشة')}<input className="code-input" value={entry} onChange={e=>setEntry(e.target.value.toUpperCase())} placeholder="UTAS-123456" required autoComplete="off" autoCapitalize="characters" spellCheck={false} inputMode="text"/></label><button className="btn primary full-width">{tr('Find workshop','ابحث عن الورشة')} <ArrowRight size={18}/></button>{(error||loadError)&&<div role="alert" className="error">{error||loadError}</div>}{code&&!loadError&&<p className="connecting"><span className="spinner"/>{tr('Connecting to your workshop…','جارٍ الاتصال بالورشة…')}</p>}</form></main>;

 const c=data.config,stage=c.stage,step=lessonIndex(stage),parent=data.ideas.find(i=>i.id===c.spotlight&&i.status==='approved');const room=data.parent;const guest=data.me?.role==='guest';const submitted=!c.multiple&&data.me?.submitted.includes(types[stage]);const teamCount=data.ideas.filter(i=>i.type!=='comment'&&i.status==='approved').length;

 if(!data.me&&room)return <main className="center-page join-entry" dir={ar?'rtl':'ltr'}><div className="page-top"><Brand/><div className="actions"><LanguageSwitch lang={lang} onChange={chooseLang}/><ThemeSwitch/></div></div><span className="eyebrow" dir="ltr">{code}</span><h1><DoorOpen size={30}/> {c.name}</h1><p>{tr('A team room in','غرفة فريق ضمن')} <strong>{room.name}</strong></p><div className="challenge-card"><span className="eyebrow">{tr('THIS TEAM’S PROJECT','مشروع هذا الفريق')}</span><h2>{c.challenge}</h2><p>{c.question}</p><span className="pill lime"><Users size={14}/> {data.stats.participants} {tr('members','أعضاء')}</span></div>{c.ended?<div className="panel">{tr('This workshop has ended. Thank you for your interest.','انتهت هذه الورشة. شكراً لاهتمامك.')}</div>:<form className="panel stack" onSubmit={e=>{e.preventDefault();void run({action:'join',nickname},()=>setWelcome(true))}}>{data.viewer?<p>{tr('You will join as','ستنضم باسم')} <strong>{data.viewer.nickname}</strong></p>:<><label>{tr('What should we call you?','ماذا نناديك؟')}<input value={nickname} maxLength={40} placeholder={ar?'اسمك المستعار':'Your nickname'} onChange={e=>setNickname(e.target.value)} required={!c.anonymous} autoComplete="nickname"/></label><small className="muted">{tr('A first name or nickname is enough. No account or password needed.','يكفي الاسم الأول أو اسم مستعار. لا حاجة لحساب أو كلمة مرور.')}</small></>}<button className="btn primary full-width" disabled={busy}>{tr('Join this team','انضم لهذا الفريق')} <Users size={18}/></button>{room.gallery&&!data.locked&&<button type="button" className="btn secondary full-width" disabled={busy} onClick={()=>void run({action:'joinRoom',role:'guest',nickname})}><Eye size={17}/>{tr('Just visit — read and comment','زيارة فقط — قراءة وتعليق')}</button>}<a className="btn ghost" href={'?code='+room.code}><ArrowLeft size={16}/>{tr('Main workshop','الورشة الرئيسية')}</a>{error&&<div role="alert" className="error">{error}</div>}</form>}</main>;

 if(!data.me)return <main className="center-page join-entry" dir={ar?'rtl':'ltr'}><div className="page-top"><Brand/><div className="actions"><LanguageSwitch lang={lang} onChange={chooseLang}/><ThemeSwitch/></div></div><NewHereBanner lang={lang}/><span className="eyebrow" dir="ltr">{code}</span><h1>{tr('Welcome to the team','مرحباً بك في الفريق')} 👋</h1><p>{tr('You are joining','أنت تنضم إلى')}</p><div className="challenge-card"><span className="eyebrow">{tr('TODAY’S CHALLENGE','تحدي اليوم')}</span><h2>{c.challenge}</h2><p>{c.question}</p><span className="pill lime"><Users size={14}/> {data.stats.participants} {tr('already joined','انضموا بالفعل')}</span></div>{c.ended?<div className="panel">{tr('This workshop has ended. Thank you for your interest.','انتهت هذه الورشة. شكراً لاهتمامك.')}</div>:<form className="panel stack" onSubmit={e=>{e.preventDefault();void run({action:'join',nickname},()=>setWelcome(true))}}><label>{tr('What should we call you?','ماذا نناديك؟')}<input value={nickname} maxLength={40} placeholder={ar?'اسمك المستعار':'Your nickname'} onChange={e=>setNickname(e.target.value)} required={!c.anonymous} autoComplete="nickname"/></label><small className="muted">{tr('A first name or nickname is enough. No account or password needed.','يكفي الاسم الأول أو اسم مستعار. لا حاجة لحساب أو كلمة مرور.')}</small><button className="btn primary full-width" disabled={busy}>{tr('Join the team','انضم إلى الفريق')} <Users size={18}/></button>{c.anonymous&&<button type="button" className="btn ghost" disabled={busy} onClick={()=>void run({action:'join',nickname:''},()=>setWelcome(true))}>{tr('Continue anonymously','المتابعة دون اسم')}</button>}{error&&<div role="alert" className="error">{error}</div>}</form>}</main>;

 const me=data.me;
 // A room lead runs the room with the presenter's guided tools, inside the student page.
 if(leading&&data.isPresenter&&room)return <Console code={code} onExit={()=>setLeading(false)}/>;
 const roomsTab=!room&&!!data.rooms&&(c.teamRooms||data.rooms.length>0);
 // With team rooms on, a student without a team starts on the Team rooms tab to pick or create one.
 const activeTab=tab==='auto'?(roomsTab&&!me.room?'rooms':'task'):tab;
 const insertStarter=(starter:string)=>{setText(v=>!v.trim()?starter:v.replace(/\s*$/,'')+'\n'+starter);requestAnimationFrame(()=>{const el=textArea.current;if(el){el.focus();el.setSelectionRange(el.value.length,el.value.length)}})};
 const submit=()=>{const id=submissionId.current;void run({action:'submit',id,title,text:stage===4?kind+': '+text:text},()=>{submissionId.current=uid();setText('');setTitle('');try{sessionStorage.removeItem(draftKey)}catch{}setCelebrate(n=>n+1);setConfirmation(c.moderated?(ar?'تم إرسال مشاركتك لمراجعة مقدم الورشة.':'Your contribution is awaiting presenter approval.'):(ar?'مشاركتك أصبحت جزءاً من مشروعنا الجماعي.':'Your contribution is now part of our collective project.'))})};
 const intro=stage===1?tr('Great products begin with a problem. What do students need help with?','تبدأ المنتجات الرائعة بمشكلة. ما الذي يحتاج الطلاب إلى المساعدة فيه؟'):stage===2?tr('Think freely. What useful idea could address our challenge?','فكر بحرية. ما الفكرة المفيدة التي يمكن أن تعالج تحدينا؟'):stage===3?tr('How could we solve this problem?','كيف يمكننا حل هذه المشكلة؟'):stage===4?tr('Don’t create a new idea. Build on this one.','لا تنشئ فكرة جديدة. بل طور هذه الفكرة.'):tr('What final feature would make our product more useful?','ما الميزة الأخيرة التي ستجعل منتجنا أكثر فائدة؟');
 const votesLeft=Math.max(0,c.maxVotes-me.votes.length);

 return <main className={'student'+(activeTab==='wall'?' student-explore':'')} dir={ar?'rtl':'ltr'} lang={ar?'ar':'en'}>
  <Celebrate run={celebrate}/>
  <header><Brand/><div className="actions"><LanguageSwitch lang={lang} onChange={chooseLang}/><ThemeSwitch/></div></header>
  <div className="student-status"><span className="eyebrow">{tr(`STEP ${step+1} OF 5`,`الخطوة ${step+1} من 5`)} · {ar?lessonSteps[step][1]:lessonSteps[step][0]}</span><span className={'connection '+(!connected?'bad':'')}>{connected?<Wifi size={13}/>:<WifiOff size={13}/>}{connected?tr('Live','مباشر'):tr('Reconnecting…','إعادة الاتصال…')}</span></div>
  <Journey step={step} lang={lang}/>
  <TranslationNotice data={data} lang={lang}/>
  {room&&<RoomBanner data={data} lang={lang} onLead={()=>setLeading(true)} refresh={refresh}/>}
  <Broadcast text={room?room.broadcast:c.broadcast} lang={lang}/>
  <nav className="student-tabs" aria-label={ar?'مساحة الورشة':'Workshop workspace'}><button className={activeTab==='task'?'active':''} aria-pressed={activeTab==='task'} onClick={()=>setTab('task')}>{guest?tr('About this room','عن هذه الغرفة'):tr('Your task','مهمتك')}</button><button className={activeTab==='wall'?'active':''} aria-pressed={activeTab==='wall'} onClick={()=>setTab('wall')}>{room?tr('Room ideas','أفكار الغرفة'):tr('Team ideas','أفكار الفريق')} <span className="pill">{teamCount}</span></button>{room&&<button className={activeTab==='files'?'active':''} aria-pressed={activeTab==='files'} onClick={()=>setTab('files')}>{tr('Files','الملفات')} <span className="pill">{data.uploads?.length||0}</span></button>}{roomsTab&&<button className={activeTab==='rooms'?'active':''} aria-pressed={activeTab==='rooms'} onClick={()=>setTab('rooms')}>{tr('Team rooms','غرف الفرق')} <span className="pill">{data.rooms!.length}</span></button>}</nav>
  <Timer end={c.timerEnd}/>
  {data.locked?<div className="waiting locked-room"><div className="waiting-icon"><Lock size={30}/></div><h1>{tr('This room is private','هذه الغرفة خاصة')}</h1><p>{tr('This team has chosen to keep its discussion to itself or to invited teams only. You can still see it on the map.','اختار هذا الفريق أن يبقي نقاشه لنفسه أو للفرق المدعوة فقط. ويمكنك رؤيته على الخريطة.')}</p><a className="btn primary full-width" href={'?code='+room!.code}><ArrowLeft size={17}/>{tr('Back to the main workshop','العودة إلى الورشة الرئيسية')}</a></div>:activeTab==='files'&&room?<RoomFiles data={data} lang={lang} refresh={refresh} canUpload={!guest&&!c.ended} manage={data.isPresenter}/>:activeTab==='rooms'&&roomsTab?<StudentRooms data={data} lang={lang}/>:activeTab==='wall'?<StudentWall data={data} lang={lang} refresh={refresh}/>:guest&&!c.ended?<div className="waiting"><div className="waiting-icon"><Eye size={30}/></div><h1>{c.challenge}</h1><p>{c.question}</p><p>{tr(`This team is at step: ${prompts[stage]}`,`هذا الفريق في مرحلة: ${promptsAr[stage]}`)}</p><button className="btn primary full-width" onClick={()=>setTab('wall')}>{tr('Read their ideas & comment','اقرأ أفكارهم وعلّق')} <ArrowRight size={18}/></button></div>:<>
  {c.ended?<div className="waiting"><div className="waiting-icon"><Sparkles size={30}/></div><h1>{tr('We created this together.','لقد ابتكرنا هذا معاً.')}</h1><p>{tr('Thank you for thinking, sharing and building with your team.','شكراً لتفكيرك ومشاركتك وبنائك مع فريقك.')}</p><h2>{c.challenge}</h2><div className="ended-stats"><span><strong>{data.stats.participants}</strong>{tr('teammates','زملاء')}</span><span><strong>{data.stats.ideas}</strong>{tr('ideas','أفكار')}</span><span><strong>{data.stats.improvements}</strong>{tr('improvements','تحسينات')}</span></div><p>{tr('This is the future of work.','هذا هو مستقبل العمل.')}</p></div>
  :c.paused?<div className="waiting"><div className="waiting-icon pulse-ring"><Pause size={30}/></div><h1>{tr('A moment to think','لحظة للتفكير')}</h1><p>{tr('The presenter has paused the workshop. Your contributions are saved.','أوقف مقدم الورشة النشاط مؤقتاً. مشاركاتك محفوظة.')}</p></div>
  :welcome?<div className="waiting"><div className="waiting-icon"><Check size={32}/></div><h1>{tr('You’re in!','أنت معنا!')} 🚀</h1><p>{tr('Today you’re not just attending a workshop. You’re joining an innovation team.','اليوم أنت لا تحضر ورشة فقط. بل تنضم إلى فريق ابتكار.')}</p><ol className="welcome-steps">{lessonSteps.map(s=><li key={s[0]}>{ar?s[1]:s[0]}</li>)}</ol><button className="btn primary full-width" onClick={()=>setWelcome(false)}>{tr('Let’s build','لنبدأ البناء')} <ArrowRight size={18}/></button></div>
  :<>{!room&&<><MyRoomLink data={data} lang={lang}/><ShowcaseVote data={data} lang={lang} refresh={refresh}/></>}{room&&me.role==='lead'&&stage===0&&<div className="success"><Crown size={16}/> {tr('Your team is waiting for you. Choose “Lead the room” to start the first step.','فريقك بانتظارك. اختر «قيادة الغرفة» لبدء الخطوة الأولى.')}</div>}<h1><T en={prompts[stage]} ar={promptsAr[stage]} lang={lang}/></h1>
  {stage===0&&<div className="waiting"><div className="waiting-icon pulse-ring"><Users size={32}/></div><h2>{c.challenge}</h2><p>{c.question}</p><p>{room?tr('You’re ready. Your next task appears when your room lead or the presenter starts.','أنت جاهز. ستظهر مهمتك التالية عندما يبدأ قائد الغرفة أو مقدم الورشة.'):tr('You’re ready. Your next task will appear when the presenter begins.','أنت جاهز. ستظهر مهمتك التالية عندما يبدأ مقدم الورشة.')}</p><span className="pill lime">{data.stats.participants} {tr('teammates joined','مشارك انضم')}</span></div>}
  {[1,2,3,4,7].includes(stage)&&<><p>{intro}</p>{(stage===1||stage===2)&&<div className="panel question-panel"><span className="eyebrow">{tr('THE CHALLENGE','التحدي')}</span><h3>{c.question}</h3></div>}{(stage===3||stage===4)&&parent&&<div className="idea-card selected spotlight-card"><div className="idea-top"><span className="pill lime">{tr('Selected idea','الفكرة المختارة')}</span><TypeChip type={parent.type} lang={lang}/></div><h3>{parent.title}</h3><p>{parent.text}</p><small className="muted">{parent.nickname}</small></div>}
  {(stage===3||stage===4)&&!parent?<div className="waiting"><div className="waiting-icon pulse-ring"><Lightbulb size={30}/></div><p>{tr('Waiting for the presenter to select an idea…','ننتظر أن يختار مقدم الورشة فكرة…')}</p></div>
  :confirmation||submitted?<div className="success success-card" role="status"><span className="success-icon"><Check size={24}/></span><h2>{tr('Great contribution!','مشاركة رائعة!')}</h2><p>{confirmation||tr('Your contribution is part of our collective project.','مشاركتك أصبحت جزءاً من مشروعنا الجماعي.')}</p>{c.multiple&&<button className="btn secondary full-width" onClick={()=>setConfirmation('')}>{tr('Add another contribution','أضف مشاركة أخرى')}</button>}<button className="btn primary full-width" onClick={()=>setTab('wall')}>{tr('Explore team ideas & comments','تصفح أفكار الفريق وتعليقاته')}</button><p className="muted">{tr('Your next task appears when the presenter changes the stage.','تظهر مهمتك التالية عندما يغيّر مقدم الورشة المرحلة.')}</p></div>
  :!c.submissionsOpen?<div className="panel">{tr('Submissions are closed. Keep your idea ready for the next stage.','تم إغلاق المشاركات. احتفظ بفكرتك للمرحلة القادمة.')}</div>
  :<><Coach key={stage} stage={stage} lang={lang} onStarter={insertStarter}/><form className="stack" onSubmit={e=>{e.preventDefault();submit()}}>{stage===4&&<div className="skill-grid">{kinds.map((v,i)=><button type="button" key={v} aria-pressed={kind===v} className={'btn '+(kind===v?'primary':'secondary')} onClick={()=>setKind(v)}>{tr(['➕ Add something','✨ Improve it','⚠️ Find a weakness','💡 Suggest an alternative'][i],['➕ أضف شيئاً','✨ حسّنها','⚠️ ابحث عن نقطة ضعف','💡 اقترح بديلاً'][i])}</button>)}</div>}{stage!==4&&<label>{tr('A short title (optional)','عنوان قصير (اختياري)')}<input value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} placeholder={ar?'سمِّ فكرتك':'Give your idea a name'}/></label>}<label>{tr('Your contribution','مشاركتك')}<textarea ref={textArea} value={text} maxLength={1500} minLength={3} required onChange={e=>setText(e.target.value)} placeholder={ar?'اكتب فكرتك هنا…':'Write your idea here…'}/></label><QualityMeter text={text} lang={lang}/><small className="muted">{text.length}/1500 · {tr('Please do not share personal or sensitive information. Your draft is kept on this device until you submit.','يرجى عدم مشاركة معلومات شخصية أو حساسة. تُحفظ مسودتك على هذا الجهاز حتى ترسلها.')}</small><button disabled={busy||text.trim().length<3} className="btn primary full-width btn-lg"><Send size={18}/>{busy?tr('Saving…','جارٍ الحفظ…'):tr(stage===3?'Submit solution':stage===4?'Submit improvement':'Submit idea',stage===3?'أرسل الحل':stage===4?'أرسل التحسين':'أرسل الفكرة')}</button></form></>}
  {stage===4&&parent&&data.ideas.filter(i=>i.parent===parent.id&&i.type==='improvement'&&i.status==='approved').map(i=><div className="indent" key={i.id}><p>{i.text}</p><small className="muted">{i.nickname}</small></div>)}</>}
  {stage===5&&<><p>{tr('Which solution creates the most value?','أي حل يقدم أكبر قيمة؟')}</p><div className="vote-budget" aria-label={ar?'أصواتك':'Your votes'}><Vote size={18}/><span>{tr(`${votesLeft} of ${c.maxVotes} votes left`,`تبقى ${votesLeft} من ${c.maxVotes} أصوات`)}</span><span className="vote-dots">{Array.from({length:c.maxVotes},(_,i)=><i key={i} className={i<me.votes.length?'used':''}/>)}</span></div>{!c.votingOpen?<div className="success">{tr('Voting is closed. Thank you for helping your team decide.','التصويت مغلق. شكراً لمساعدة فريقك في اتخاذ القرار.')}</div>:<p className="inline-help">{tr('Consider value for users, feasibility, and responsibility. One vote per idea.','فكّر في القيمة للمستخدمين وقابلية التنفيذ والمسؤولية. صوت واحد لكل فكرة.')}</p>}{data.ideas.filter(i=>i.shortlisted&&i.status==='approved').map(i=>{const voted=me.votes.includes(i.id);return <div className={'idea-card vote-card'+(voted?' selected':'')} key={i.id}><div className="idea-top"><TypeChip type={i.type} lang={lang}/>{voted&&<span className="pill lime">✓ {tr('Your vote','صوتك')}</span>}</div><h3>{i.title}</h3><p>{i.text}</p><button disabled={busy||!c.votingOpen||voted||me.votes.length>=c.maxVotes} className={'btn '+(voted?'secondary':'primary')} onClick={()=>void run({action:'vote',id:i.id},()=>setCelebrate(n=>n+1))}>{voted?tr('Vote saved ✓','تم حفظ صوتك ✓'):tr('Vote for this idea','صوّت لهذه الفكرة')}</button></div>})}{c.liveResults&&<Results data={data} lang={lang}/>}</>}
  {stage===6&&<><div className="human-ai-flow"><div><span>👥</span><h3>{tr('Human','الإنسان')}</h3><p>{tr('Problems · experience · creativity · judgment','المشكلات · الخبرة · الإبداع · الحكم')}</p></div><div><span>🤖</span><h3>{tr('AI','الذكاء الاصطناعي')}</h3><p>{tr('Organize · analyze · combine · suggest','التنظيم · التحليل · الدمج · الاقتراح')}</p></div><div><span>👥</span><h3>{tr('Human','الإنسان')}</h3><p>{tr('Evaluate · correct · decide','التقييم · التصحيح · القرار')}</p></div></div><div className="success">{tr('AI does not replace thinking. AI amplifies good thinking.','الذكاء الاصطناعي لا يستبدل التفكير. بل يعزز التفكير الجيد.')}</div><HumanAiQuiz lang={lang}/></>}
  {stage===7&&<>{data.ideas.filter(i=>c.selected.includes(i.id)&&i.status==='approved').length>0&&<div className="section-heading"><h2>{tr('Our product’s core features','الميزات الأساسية لمنتجنا')}</h2></div>}{data.ideas.filter(i=>c.selected.includes(i.id)&&i.status==='approved').map(i=><div className="idea-card selected" key={i.id}><h3>✓ {i.title}</h3><p>{i.text}</p></div>)}<HumanAiQuiz lang={lang}/></>}
  {stage===8&&<><p>{tr('Which skill will be most important in your future career?','ما المهارة الأهم في مسيرتك المهنية المستقبلية؟')}</p><div className="skill-grid">{skills.map((skill,i)=><button disabled={busy} key={skill} aria-pressed={me.reflection===skill} className={'btn '+(me.reflection===skill?'primary':'secondary')} onClick={()=>void run({action:'reflect',skill})}>{skillIcons[i]} {tr(skill,skillArabic[i])}</button>)}</div>{me.reflection&&<><ReflectionInsight skill={me.reflection} lang={lang}/><p className="inline-help">{tr('Your reflection is saved. You can change your choice.','تم حفظ إجابتك. يمكنك تغيير اختيارك.')}</p></>}<div className="section-heading"><h2>{tr('Our team’s future skills','مهارات فريقنا المستقبلية')}</h2></div><Results data={data} reflection lang={lang}/></>}
  </>}</>}
  {error&&<div role="alert" className="error">{error}</div>}{loadError&&<div role="alert" className="error">{loadError}</div>}
  <p className="inline-help student-footer">{tr('Connected as','متصل باسم')} <strong>{me.nickname}</strong> · <span dir="ltr">{code}</span></p>
 </main>;
}
